use [$(APP_DB_NAME)];
DECLARE @DBSCHEMA VARCHAR(255);

SET @DBSCHEMA = '$(DB_SCHEMA)';

DECLARE @SQL_SCRIPT2 VARCHAR(MAX)
DECLARE @USER_TEMPLATE VARCHAR(MAX)

SET @USER_TEMPLATE = 'IF NOT EXISTS(SELECT * FROM sys.schemas WHERE name = N''{{DBSCHEMA}}'') BEGIN; EXEC(''CREATE SCHEMA [{{DBSCHEMA}}]''); END;'
SET @SQL_SCRIPT2 = REPLACE(@USER_TEMPLATE, '{{DBSCHEMA}}', @DBSCHEMA)
EXECUTE (@SQL_SCRIPT2)