USE [$(APP_DB_NAME)]
GO

DECLARE @DBNAME VARCHAR(255);
DECLARE @DBUSER VARCHAR(255);
DECLARE @DBPASSWORD VARCHAR(255);

SET @DBNAME = '$(APP_DB_NAME)';
SET @DBUSER = '$(APP_DB_USER)';
SET @DBPASSWORD = '$(APP_DB_PASSWORD)';

DECLARE @SQL_SCRIPT2 VARCHAR(MAX)
DECLARE @USER_TEMPLATE VARCHAR(MAX)

SET @USER_TEMPLATE = '
IF NOT EXISTS(SELECT * FROM sys.syslogins WHERE name = ''{{DBUSER}}'') 
BEGIN; 
    CREATE LOGIN [{{DBUSER}} ]
        WITH PASSWORD=N''{{DBPASSWORD}}'',
        DEFAULT_DATABASE=[{{DBNAME}}], 
        CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF; 
END;'
SET @SQL_SCRIPT2 = REPLACE(@USER_TEMPLATE, '{{DBUSER}}', @DBUSER)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{DBNAME}}', @DBNAME)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{DBPASSWORD}}', @DBPASSWORD)
EXECUTE (@SQL_SCRIPT2)