USE [aah_legacy];
GO

DECLARE @DBNAME VARCHAR(255);
DECLARE @SALOGIN VARCHAR(255);
DECLARE @SAPASSWORD VARCHAR(255);

SET @DBNAME = '$(APP_DB_NAME)';
SET @SALOGIN = '$(APP_SA_LOGIN)';
SET @SAPASSWORD = '$(APP_SA_PASSWORD)';

DECLARE @SQL_SCRIPT2 VARCHAR(MAX)
DECLARE @USER_TEMPLATE VARCHAR(MAX)

SET @USER_TEMPLATE = '
USE [aah_legacy];

PRINT ''Creating the {{SALOGIN}} for the aah_legacy database''
IF DATABASE_PRINCIPAL_ID(''{{SALOGIN}}'') IS NULL 
BEGIN; 
   CREATE USER [{{SALOGIN}}] FOR LOGIN [{{SALOGIN}}];
END;
ALTER ROLE [db_datareader] ADD MEMBER [{{SALOGIN}}];
ALTER ROLE [db_datawriter] ADD MEMBER [{{SALOGIN}}];
'
SET @SQL_SCRIPT2 = REPLACE(@USER_TEMPLATE, '{{SALOGIN}}', @SALOGIN)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{SAPASSWORD}}', @SAPASSWORD)
EXECUTE (@SQL_SCRIPT2)