USE [$(APP_DB_NAME)]
GO

DECLARE @DBNAME VARCHAR(255);
DECLARE @DBSCHEMA VARCHAR(255);
DECLARE @DBUSER VARCHAR(255);
DECLARE @DBPASSWORD VARCHAR(255);

SET @DBNAME = '$(APP_DB_NAME)';
SET @DBUSER = '$(APP_DB_USER)';
SET @DBSCHEMA = '$(DB_SCHEMA)';

DECLARE @USER_TEMPLATE VARCHAR(MAX)
DECLARE @SQL_SCRIPT2 VARCHAR(MAX)

SET @USER_TEMPLATE = '
IF DATABASE_PRINCIPAL_ID(''{{DBUSER}}'') IS NULL 
BEGIN; 
    CREATE USER [{{DBUSER}}] FOR LOGIN [{{DBUSER}}]; 
    ALTER AUTHORIZATION ON SCHEMA::[{{DBSCHEMA}}] TO [{{DBUSER}}]
    ALTER ROLE [db_datareader] ADD MEMBER [{{DBUSER}}];
    ALTER ROLE [db_datawriter] ADD MEMBER [{{DBUSER}}];
END;'
SET @SQL_SCRIPT2 = REPLACE(@USER_TEMPLATE, '{{DBUSER}}', @DBUSER)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{DBNAME}}', @DBNAME)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{DBSCHEMA}}', @DBSCHEMA)
EXECUTE (@SQL_SCRIPT2)

