DECLARE @DBNAME VARCHAR(255);
DECLARE @DBUSER VARCHAR(255);
DECLARE @DBPASSWORD VARCHAR(255);
DECLARE @DBSCHEMA VARCHAR(255);
DECLARE @DBLOGIN VARCHAR(255);

SET @DBNAME = '$(APP_DB_NAME)';
SET @DBLOGIN = '$(APP_SA_LOGIN)';
SET @DBUSER = '$(APP_SA_USER)';
SET @DBSCHEMA = '$(DB_SCHEMA)';

DECLARE @USER_TEMPLATE VARCHAR(MAX)
DECLARE @SQL_SCRIPT2 VARCHAR(MAX)

SET @USER_TEMPLATE = '
USE [{{DBNAME}}];
IF DATABASE_PRINCIPAL_ID(''{{DBUSER}}'') IS NULL 
BEGIN; 
    PRINT ''Creating user {{DBUSER}} from login {{DBLOGIN}} for the {{DBNAME}} database''
    CREATE USER [{{DBUSER}}] FOR LOGIN [{{DBLOGIN}}]; 
END;

USE [aah_legacy];
IF DATABASE_PRINCIPAL_ID(''{{DBUSER}}'') IS NULL 
BEGIN; 
    PRINT ''Creating user {{DBUSER}} from login {{DBLOGIN}} for the aah_legacy database''
    CREATE USER [{{DBUSER}}] FOR LOGIN [{{DBLOGIN}}]; 
END;

ALTER ROLE [db_datareader] ADD MEMBER [{{DBUSER}}];
ALTER ROLE [db_datawriter] ADD MEMBER [{{DBUSER}}];
'
SET @SQL_SCRIPT2 = REPLACE(@USER_TEMPLATE, '{{DBUSER}}', @DBUSER)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{DBLOGIN}}', @DBLOGIN)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{DBNAME}}', @DBNAME)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{DBSCHEMA}}', @DBSCHEMA)
EXECUTE (@SQL_SCRIPT2)

