USE [master]
GO

DECLARE @DBNAME VARCHAR(255);
DECLARE @DBUSER VARCHAR(255);
DECLARE @DBPASSWORD VARCHAR(255);

SET @DBNAME = '$(APP_DB_NAME)';
SET @DBUSER = '$(APP_DB_USER)';
SET @DBPASSWORD = '$(APP_DB_PASSWORD)';

DECLARE @CREATE_TEMPLATE VARCHAR(MAX)
DECLARE @SQL_SCRIPT1 VARCHAR(MAX)

SET @CREATE_TEMPLATE = 'IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = ''{{DBNAME}}'') BEGIN; CREATE DATABASE {{DBNAME}}; END;'
SET @SQL_SCRIPT1 = REPLACE(@CREATE_TEMPLATE, '{{DBNAME}}', @DBNAME)
EXECUTE (@SQL_SCRIPT1)
