USE [$(APP_DB_NAME)];
DECLARE @DBNAME VARCHAR(255);
DECLARE @SAUSER VARCHAR(255);
DECLARE @SAPASSWORD VARCHAR(255);

SET @SAUSER = '$(APP_SA_USER)';
SET @DBNAME = '$(APP_DB_NAME)';

DECLARE @SQL_SCRIPT2 VARCHAR(MAX)
DECLARE @USER_TEMPLATE VARCHAR(MAX)

SET @USER_TEMPLATE = '
PRINT ''Deny admin level user: {{SAUSER}} ability to alter dbo schema''
USE [{{DBNAME}}];
DENY ALTER ON SCHEMA::[dbo] to [{{SAUSER}}];
'

SET @SQL_SCRIPT2 = REPLACE(@USER_TEMPLATE, '{{SAUSER}}', @SAUSER)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{DBNAME}}', @DBNAME)
EXECUTE (@SQL_SCRIPT2)