USE [master]
GO

DECLARE @DBNAME VARCHAR(255);
DECLARE @DBUSER VARCHAR(255);
DECLARE @DBPASSWORD VARCHAR(255);

SET @DBNAME = '$(APP_DB_NAME)';

DECLARE @CREATE_TEMPLATE VARCHAR(MAX)
DECLARE @SQL_SCRIPT1 VARCHAR(MAX)

SET @CREATE_TEMPLATE = '
PRINT ''Dropping and creating the {{DBNAME}} database...''
IF EXISTS(SELECT * FROM sys.databases WHERE name = ''{{DBNAME}}'')
BEGIN;
    ALTER DATABASE {{DBNAME}} SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE {{DBNAME}}; 
END; 
CREATE DATABASE {{DBNAME}};'
SET @SQL_SCRIPT1 = REPLACE(@CREATE_TEMPLATE, '{{DBNAME}}', @DBNAME)
EXECUTE (@SQL_SCRIPT1)
