DECLARE @DBNAME VARCHAR(255);
DECLARE @DBUSER VARCHAR(255);
DECLARE @DBSCHEMA VARCHAR(255);

SET @DBUSER = '$(APP_SA_USER)';
SET @DBNAME = '$(APP_DB_NAME)';
SET @DBSCHEMA = '$(DB_SCHEMA)';

DECLARE @USER_TEMPLATE VARCHAR(MAX)
DECLARE @SQL_SCRIPT2 VARCHAR(MAX)

SET @USER_TEMPLATE = '
USE [{{DBNAME}}];
IF DATABASE_PRINCIPAL_ID(''{{DBUSER}}'') IS NOT NULL 
BEGIN; 
    PRINT ''Apply ability to create table, alter schema, deny dbo alter, db_ddladmin, db_datareader and db_datawriter grants to {{DBUSER}}''
    ALTER ROLE [db_ddladmin] ADD MEMBER [{{DBUSER}}];
    ALTER ROLE [db_datareader] ADD MEMBER [{{DBUSER}}];
    ALTER ROLE [db_datawriter] ADD MEMBER [{{DBUSER}}];
    GRANT ALTER ON SCHEMA::[{{DBSCHEMA}}] TO [{{DBUSER}}];
    GRANT CREATE TABLE TO [{{DBUSER}}]; 
    GRANT CREATE VIEW TO [{{DBUSER}}]; 
    GRANT EXECUTE TO [{{DBUSER}}];
    DENY ALTER ON SCHEMA::[dbo] TO [{{DBUSER}}]; 
END;'
SET @SQL_SCRIPT2 = REPLACE(@USER_TEMPLATE, '{{DBUSER}}', @DBUSER)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{DBNAME}}', @DBNAME)
SET @SQL_SCRIPT2 = REPLACE(@SQL_SCRIPT2, '{{DBSCHEMA}}', @DBSCHEMA)
EXECUTE (@SQL_SCRIPT2)

