/****** Object:  Table [dbo].[AAH_CNTCT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_CNTCT](
	[AAH_CNTCT_ID] [int] NOT NULL,
	[TXDOT_CNTY_NBR] [numeric](3, 0) NOT NULL,
	[CNTCT_PRFX_NM] [varchar](20) NULL,
	[CNTCT_FRST_NM] [varchar](30) NULL,
	[CNTCT_MIDL_NM] [varchar](30) NULL,
	[CNTCT_LAST_NM] [varchar](30) NULL,
	[CNTCT_SFX_NM] [varchar](20) NULL,
	[CNTCT_CRDNTL_NM] [varchar](20) NULL,
	[CNTCT_PRFR_NM] [varchar](30) NULL,
	[CNTCT_ML_ADDR1] [varchar](50) NULL,
	[CNTCT_ML_ADDR2] [varchar](50) NULL,
	[CNTCT_ML_CITY_NM] [varchar](50) NULL,
	[CNTCT_ML_STATE_ABRVN_NM] [char](2) NULL,
	[CNTCT_ML_ZIPCD] [varchar](10) NULL,
	[CNTCT_PHYS_ADDR1] [varchar](50) NULL,
	[CNTCT_PHYS_ADDR2] [varchar](50) NULL,
	[CNTCT_PHYS_CITY_NM] [varchar](50) NULL,
	[CNTCT_PHYS_STATE_ABRVN_NM] [char](2) NULL,
	[CNTCT_PHYS_ZIPCD] [varchar](10) NULL,
	[CNTCT_DAYTM_AREA_CD] [char](3) NULL,
	[CNTCT_DAYTM_PHN_NBR] [char](8) NULL,
	[CNTCT_ALT1_AREA_CD] [char](3) NULL,
	[CNTCT_ALT1_PHN_NBR] [char](8) NULL,
	[CNTCT_ALT2_AREA_CD] [char](3) NULL,
	[CNTCT_ALT2_PHN_NBR] [char](8) NULL,
	[CNTCT_FAX_AREA_CD] [char](3) NULL,
	[CNTCT_FAX_PHN_NBR] [char](8) NULL,
	[CNTCT_EML_ADDR] [varchar](50) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
	[CNTCT_DAYTM_EXT_NBR] [varchar](5) NULL,
	[CNTCT_DAYTM_PHN_CMNT] [varchar](50) NULL,
	[CNTCT_ALT1_EXT_NBR] [varchar](5) NULL,
	[CNTCT_ALT1_PHN_CMNT] [varchar](50) NULL,
	[CNTCT_ALT2_EXT_NBR] [varchar](5) NULL,
	[CNTCT_ALT2_PHN_CMNT] [varchar](50) NULL,
 CONSTRAINT [PK__AAH_CNTCT__7A9C383C] PRIMARY KEY CLUSTERED 
(
	[AAH_CNTCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_CNTCT_TYPE]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_CNTCT_TYPE](
	[AAH_CNTCT_TYPE_NM] [varchar](50) NOT NULL,
	[AAH_CNTCT_TYPE_DSCR] [varchar](200) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__AAH_CNTCT_TYPE__7C8480AE] PRIMARY KEY CLUSTERED 
(
	[AAH_CNTCT_TYPE_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_CNTRCT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_CNTRCT](
	[AAH_CNTRCT_ID] [int] NOT NULL,
	[AAH_GRP_ID] [int] NOT NULL,
	[AAH_SGMNT_ID] [int] NOT NULL,
	[AAH_CNTRCT_SEQN_NBR] [int] NULL,
	[AAH_CNTRCT_START_DT] [datetime] NULL,
	[AAH_CNTRCT_EXPIR_DT] [datetime] NULL,
	[AAH_CNTRCT_STAT_NM] [varchar](50) NOT NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__AAH_CNTRCT__0F975522] PRIMARY KEY CLUSTERED 
(
	[AAH_CNTRCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_CNTRCT_EVNT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_CNTRCT_EVNT](
	[AAH_CNTRCT_EVNT_NM] [varchar](50) NOT NULL,
	[AAH_CNTRCT_EVNT_DSCR] [varchar](200) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__AAH_CNTRCT_EVNT__117F9D94] PRIMARY KEY CLUSTERED 
(
	[AAH_CNTRCT_EVNT_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_CNTRCT_EVNT_LOG]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_CNTRCT_EVNT_LOG](
	[AAH_CNTRCT_ID] [int] NOT NULL,
	[AAH_CNTRCT_EVNT_NM] [varchar](50) NOT NULL,
	[AAH_CNTRCT_EVNT_LOG_DT] [datetime] NOT NULL,
	[AAH_CNTRCT_EVNT_LOG_CMNT] [varchar](500) NULL,
	[AAH_CNTRCT_SIGN_LN_1_NM] [varchar](20) NULL,
	[AAH_CNTRCT_SIGN_LN_2_NM] [varchar](20) NULL,
	[AAH_CNTRCT_SIGN_LN_3_NM] [varchar](20) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__AAH_CNTRCT_EVNT___1367E606] PRIMARY KEY CLUSTERED 
(
	[AAH_CNTRCT_ID] ASC,
	[AAH_CNTRCT_EVNT_NM] ASC,
	[AAH_CNTRCT_EVNT_LOG_DT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_CNTRCT_STAT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_CNTRCT_STAT](
	[AAH_CNTRCT_STAT_NM] [varchar](50) NOT NULL,
	[AAH_CNTRCT_STAT_DSCR] [varchar](500) NOT NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__AAH_CNTRCT_STAT__023D5A04] PRIMARY KEY CLUSTERED 
(
	[AAH_CNTRCT_STAT_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_Database_Deletions]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_Database_Deletions](
	[GroupID] [int] NULL,
	[GroupName] [varchar](60) NULL,
	[District] [varchar](50) NULL,
	[County] [varchar](50) NULL,
	[AgreementID ] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_GRP]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_GRP](
	[AAH_GRP_ID] [int] NOT NULL,
	[TXDOT_CNTY_NBR] [numeric](3, 0) NOT NULL,
	[AAH_GRP_NM] [varchar](60) NULL,
	[AAH_GRP_TYPE_NM] [varchar](20) NOT NULL,
	[AAH_GRP_ML_ADDR1] [varchar](50) NULL,
	[AAH_GRP_ML_ADDR2] [varchar](50) NULL,
	[AAH_GRP_ML_CITY_NM] [varchar](50) NULL,
	[AAH_GRP_ML_STATE_ABRVN_NM] [char](2) NULL,
	[AAH_GRP_ML_ZIPCD] [varchar](10) NULL,
	[AAH_GRP_PHYS_ADDR1] [varchar](50) NULL,
	[AAH_GRP_PHYS_ADDR2] [varchar](50) NULL,
	[AAH_GRP_PHYS_CITY_NM] [varchar](50) NULL,
	[AAH_GRP_PHYS_STATE_ABRVN_NM] [char](2) NULL,
	[AAH_GRP_PHYS_ZIPCD] [varchar](10) NULL,
	[AAH_GRP_ESTMTD_VOLR_QTY] [int] NULL,
	[AAH_GRP_APPLN_SEND_DT] [datetime] NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
	[AAH_GRP_INIT_CNTCT_DT] [datetime] NULL,
	[AAH_GRP_CMNT] [varchar](500) NULL,
	[DIST_ABRVN_NM] [varchar](3) NOT NULL,
	[MAINT_SECT_NBR] [numeric](2, 0) NOT NULL,
 CONSTRAINT [PK__AAH_GRP__00551192] PRIMARY KEY CLUSTERED 
(
	[AAH_GRP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_GRP_CNTCT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_GRP_CNTCT](
	[AAH_GRP_ID] [int] NOT NULL,
	[AAH_CNTCT_ID] [int] NOT NULL,
	[AAH_CNTCT_TYPE_NM] [varchar](50) NOT NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__AAH_GRP_CNTCT__1CF15040] PRIMARY KEY CLUSTERED 
(
	[AAH_GRP_ID] ASC,
	[AAH_CNTCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_GRP_TYPE]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_GRP_TYPE](
	[AAH_GRP_TYPE_NM] [varchar](20) NOT NULL,
	[AAH_GRP_TYPE_DSCR] [char](18) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__AAH_GRP_TYPE__7E6CC920] PRIMARY KEY CLUSTERED 
(
	[AAH_GRP_TYPE_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_SGMNT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_SGMNT](
	[AAH_SGMNT_ID] [int] NOT NULL,
	[RTE_PRFX_CD] [varchar](2) NOT NULL,
	[RTE_NBR] [varchar](4) NOT NULL,
	[RTE_SFX_NM] [varchar](1) NOT NULL,
	[FROM_TO_LMT_DSCR] [varchar](200) NULL,
	[AAH_SGMNT_LNGTH_MS] [numeric](4, 2) NULL,
	[AAH_SGMNT_ACRE_MS] [numeric](5, 2) NULL,
	[AAH_SGMNT_PICKUP_CYCL_QTY] [int] NULL,
	[AAH_SGMNT_CNSTR_FLAG] [char](1) NULL,
	[AAH_SGMNT_FROM_LAT] [numeric](11, 8) NULL,
	[AAH_SGMNT_FROM_LON] [numeric](11, 8) NULL,
	[AAH_SGMNT_FROM_EL] [numeric](5, 3) NULL,
	[AAH_SGMNT_TO_LAT] [numeric](11, 8) NULL,
	[AAH_SGMNT_TO_LON] [numeric](11, 8) NULL,
	[AAH_SGMNT_TO_EL] [numeric](5, 3) NULL,
	[AAH_SGMNT_BASE_SIGN_FLAG] [char](1) NULL,
	[AAH_SGMNT_STAT_NM] [varchar](50) NOT NULL,
	[AAH_SGMNT_CMNT] [varchar](500) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
	[MAINT_SECT_NBR] [numeric](2, 0) NOT NULL,
	[DIST_ABRVN_NM] [varchar](3) NOT NULL,
 CONSTRAINT [PK__AAH_SGMNT__0DAF0CB0] PRIMARY KEY CLUSTERED 
(
	[AAH_SGMNT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AAH_SGMNT_STAT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAH_SGMNT_STAT](
	[AAH_SGMNT_STAT_NM] [varchar](50) NOT NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__AAH_SGMNT_STAT__0BC6C43E] PRIMARY KEY CLUSTERED 
(
	[AAH_SGMNT_STAT_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CNTY]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CNTY](
	[TXDOT_CNTY_NBR] [numeric](3, 0) NOT NULL,
	[COMPT_CNTY_NBR] [numeric](3, 0) NULL,
	[DPS_CNTY_NBR] [numeric](3, 0) NULL,
	[FIPS_CNTY_NBR] [numeric](5, 0) NULL,
	[CNTY_NM] [varchar](50) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
	[DIST_ABRVN_NM] [varchar](3) NOT NULL,
 CONSTRAINT [PK__CNTY__78B3EFCA] PRIMARY KEY CLUSTERED 
(
	[TXDOT_CNTY_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DCMNT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DCMNT](
	[AAH_CNTRCT_ID] [int] NOT NULL,
	[AAH_CNTRCT_EVNT_NM] [varchar](50) NOT NULL,
	[AAH_CNTRCT_EVNT_LOG_DT] [datetime] NOT NULL,
	[DCMNT_TMPLT_NM] [varchar](50) NOT NULL,
	[DCMNT_TMPLT_VERS_NBR] [int] NOT NULL,
	[DCMNT_ADDENDUM_DSCR] [char](18) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__DCMNT__267ABA7A] PRIMARY KEY CLUSTERED 
(
	[AAH_CNTRCT_ID] ASC,
	[AAH_CNTRCT_EVNT_NM] ASC,
	[AAH_CNTRCT_EVNT_LOG_DT] ASC,
	[DCMNT_TMPLT_NM] ASC,
	[DCMNT_TMPLT_VERS_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DCMNT_TMPLT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DCMNT_TMPLT](
	[DCMNT_TMPLT_NM] [varchar](50) NOT NULL,
	[DCMNT_TMPLT_VERS_NBR] [int] NOT NULL,
	[DCMNT_TMPLT_DSCR] [varchar](200) NULL,
	[DCMNT_TMPLT_ADDR] [varchar](50) NULL,
	[DCMNT_TMPLT_STAT_NM] [varchar](50) NOT NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__DCMNT_TMPLT__24927208] PRIMARY KEY CLUSTERED 
(
	[DCMNT_TMPLT_NM] ASC,
	[DCMNT_TMPLT_VERS_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DCMNT_TMPLT_STAT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DCMNT_TMPLT_STAT](
	[DCMNT_TMPLT_STAT_NM] [varchar](50) NOT NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__DCMNT_TMPLT_STAT__22AA2996] PRIMARY KEY CLUSTERED 
(
	[DCMNT_TMPLT_STAT_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAINT_SECT]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAINT_SECT](
	[MAINT_SECT_NBR] [numeric](2, 0) NOT NULL,
	[MAINT_SECT_NM] [varchar](50) NOT NULL,
	[MAINT_SECT_ML_ADDR1] [varchar](50) NULL,
	[MAINT_SECT_ML_ADDR2] [varchar](50) NULL,
	[MAINT_SECT_ML_CITY_NM] [varchar](50) NULL,
	[MAINT_SECT_ML_STATE_ABRVN_NM] [char](2) NULL,
	[MAINT_SECT_ML_ZIPCD] [varchar](10) NULL,
	[MAINT_SECT_PHYS_ADDR1] [varchar](50) NULL,
	[MAINT_SECT_PHYS_ADDR2] [varchar](50) NULL,
	[MAINT_SECT_PHYS_CITY_NM] [varchar](50) NULL,
	[MAINT_SECT_PHYS_STATE_ABRVN_NM] [char](2) NULL,
	[MAINT_SECT_PHYS_ZIPCD] [varchar](10) NULL,
	[MAINT_SECT_HOME_PHN_NBR] [char](10) NULL,
	[MAINT_SECT_FAX_PHN_NBR] [char](10) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
	[TXDOT_CNTY_NBR] [numeric](3, 0) NOT NULL,
	[DIST_ABRVN_NM] [varchar](3) NOT NULL,
	[MAINT_SECT_CNTCT_NM] [varchar](50) NULL,
	[MAINT_SECT_CNTCT_EML_ADDR] [varchar](50) NULL,
 CONSTRAINT [PK__MAINT__10192006210404001] PRIMARY KEY CLUSTERED 
(
	[MAINT_SECT_NBR] ASC,
	[DIST_ABRVN_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PICKUP]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PICKUP](
	[AAH_CNTRCT_ID] [int] NOT NULL,
	[AAH_PICKUP_DT] [datetime] NOT NULL,
	[PICKUP_TYPE_NM] [varchar](50) NOT NULL,
	[PICKUP_BAG_FILL_QTY] [int] NULL,
	[PICKUP_VOLR_QTY] [int] NULL,
	[PICKUP_UNUSL_ITEM_DSCR] [varchar](200) NULL,
	[PICKUP_CMNT] [varchar](500) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
	[PICKUP_EXTRA_CLEANUP_FLAG] [char](1) NULL,
 CONSTRAINT [PK__PICKUP__2A4B4B5E] PRIMARY KEY CLUSTERED 
(
	[AAH_CNTRCT_ID] ASC,
	[AAH_PICKUP_DT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PICKUP_TYPE]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PICKUP_TYPE](
	[PICKUP_TYPE_NM] [varchar](50) NOT NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__PICKUP_TYPE__286302EC] PRIMARY KEY CLUSTERED 
(
	[PICKUP_TYPE_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SCHED_PICKUP]    Script Date: 9/13/2021 2:01:15 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCHED_PICKUP](
	[AAH_CNTRCT_ID] [int] NOT NULL,
	[SCHED_PICKUP_ESTMTD_MTH_YR_DT] [char](18) NOT NULL,
	[PICKUP_TYPE_NM] [varchar](50) NOT NULL,
	[SCHED_PICKUP_ACTL_SCHED_DT] [datetime] NULL,
	[SCHED_PICKUP_ESTMTD_BAG_QTY] [char](18) NULL,
	[SCHED_PICKUP_ESTMTD_VEST_QTY] [char](18) NULL,
	[CREATE_USER_ID] [varchar](8) NOT NULL,
	[CREATE_DTTM] [datetime] NOT NULL,
	[UPDT_USER_ID] [varchar](8) NOT NULL,
	[UPDT_DTTM] [datetime] NOT NULL,
 CONSTRAINT [PK__SCHED_PICKUP__2C3393D0] PRIMARY KEY CLUSTERED 
(
	[AAH_CNTRCT_ID] ASC,
	[SCHED_PICKUP_ESTMTD_MTH_YR_DT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AAH_CNTRCT]  WITH CHECK ADD  CONSTRAINT [FK__AAH_CNTRC__AAH_C__38996AB5] FOREIGN KEY([AAH_CNTRCT_STAT_NM])
REFERENCES [dbo].[AAH_CNTRCT_STAT] ([AAH_CNTRCT_STAT_NM])
GO
ALTER TABLE [dbo].[AAH_CNTRCT] CHECK CONSTRAINT [FK__AAH_CNTRC__AAH_C__38996AB5]
GO
ALTER TABLE [dbo].[AAH_CNTRCT]  WITH CHECK ADD  CONSTRAINT [FK__AAH_CNTRC__AAH_G__37A5467C] FOREIGN KEY([AAH_GRP_ID])
REFERENCES [dbo].[AAH_GRP] ([AAH_GRP_ID])
GO
ALTER TABLE [dbo].[AAH_CNTRCT] CHECK CONSTRAINT [FK__AAH_CNTRC__AAH_G__37A5467C]
GO
ALTER TABLE [dbo].[AAH_CNTRCT]  WITH CHECK ADD  CONSTRAINT [FK__AAH_CNTRC__AAH_S__7908F585] FOREIGN KEY([AAH_SGMNT_ID])
REFERENCES [dbo].[AAH_SGMNT] ([AAH_SGMNT_ID])
GO
ALTER TABLE [dbo].[AAH_CNTRCT] CHECK CONSTRAINT [FK__AAH_CNTRC__AAH_S__7908F585]
GO
ALTER TABLE [dbo].[AAH_CNTRCT_EVNT_LOG]  WITH CHECK ADD  CONSTRAINT [FK__AAH_CNTRC__AAH_C__3A81B327] FOREIGN KEY([AAH_CNTRCT_EVNT_NM])
REFERENCES [dbo].[AAH_CNTRCT_EVNT] ([AAH_CNTRCT_EVNT_NM])
GO
ALTER TABLE [dbo].[AAH_CNTRCT_EVNT_LOG] CHECK CONSTRAINT [FK__AAH_CNTRC__AAH_C__3A81B327]
GO
ALTER TABLE [dbo].[AAH_CNTRCT_EVNT_LOG]  WITH CHECK ADD  CONSTRAINT [FK__AAH_CNTRC__AAH_C__3B75D760] FOREIGN KEY([AAH_CNTRCT_ID])
REFERENCES [dbo].[AAH_CNTRCT] ([AAH_CNTRCT_ID])
GO
ALTER TABLE [dbo].[AAH_CNTRCT_EVNT_LOG] CHECK CONSTRAINT [FK__AAH_CNTRC__AAH_C__3B75D760]
GO
ALTER TABLE [dbo].[AAH_GRP]  WITH CHECK ADD  CONSTRAINT [FK__AAH_GRP__AAH_GRP__300424B4] FOREIGN KEY([AAH_GRP_TYPE_NM])
REFERENCES [dbo].[AAH_GRP_TYPE] ([AAH_GRP_TYPE_NM])
GO
ALTER TABLE [dbo].[AAH_GRP] CHECK CONSTRAINT [FK__AAH_GRP__AAH_GRP__300424B4]
GO
ALTER TABLE [dbo].[AAH_GRP_CNTCT]  WITH CHECK ADD  CONSTRAINT [FK__AAH_GRP_C__AAH_C__412EB0B6] FOREIGN KEY([AAH_CNTCT_TYPE_NM])
REFERENCES [dbo].[AAH_CNTCT_TYPE] ([AAH_CNTCT_TYPE_NM])
GO
ALTER TABLE [dbo].[AAH_GRP_CNTCT] CHECK CONSTRAINT [FK__AAH_GRP_C__AAH_C__412EB0B6]
GO
ALTER TABLE [dbo].[AAH_GRP_CNTCT]  WITH CHECK ADD  CONSTRAINT [FK__AAH_GRP_C__AAH_C__4222D4EF] FOREIGN KEY([AAH_CNTCT_ID])
REFERENCES [dbo].[AAH_CNTCT] ([AAH_CNTCT_ID])
GO
ALTER TABLE [dbo].[AAH_GRP_CNTCT] CHECK CONSTRAINT [FK__AAH_GRP_C__AAH_C__4222D4EF]
GO
ALTER TABLE [dbo].[AAH_GRP_CNTCT]  WITH CHECK ADD  CONSTRAINT [FK__AAH_GRP_C__AAH_G__403A8C7D] FOREIGN KEY([AAH_GRP_ID])
REFERENCES [dbo].[AAH_GRP] ([AAH_GRP_ID])
GO
ALTER TABLE [dbo].[AAH_GRP_CNTCT] CHECK CONSTRAINT [FK__AAH_GRP_C__AAH_G__403A8C7D]
GO
ALTER TABLE [dbo].[AAH_SGMNT]  WITH CHECK ADD  CONSTRAINT [FK__AAH_SGMNT__7CD98669] FOREIGN KEY([MAINT_SECT_NBR], [DIST_ABRVN_NM])
REFERENCES [dbo].[MAINT_SECT] ([MAINT_SECT_NBR], [DIST_ABRVN_NM])
GO
ALTER TABLE [dbo].[AAH_SGMNT] CHECK CONSTRAINT [FK__AAH_SGMNT__7CD98669]
GO
ALTER TABLE [dbo].[AAH_SGMNT]  WITH CHECK ADD  CONSTRAINT [FK__AAH_SGMNT__AAH_S__7BE56230] FOREIGN KEY([AAH_SGMNT_STAT_NM])
REFERENCES [dbo].[AAH_SGMNT_STAT] ([AAH_SGMNT_STAT_NM])
GO
ALTER TABLE [dbo].[AAH_SGMNT] CHECK CONSTRAINT [FK__AAH_SGMNT__AAH_S__7BE56230]
GO
ALTER TABLE [dbo].[DCMNT]  WITH CHECK ADD  CONSTRAINT [FK__DCMNT__47DBAE45] FOREIGN KEY([DCMNT_TMPLT_NM], [DCMNT_TMPLT_VERS_NBR])
REFERENCES [dbo].[DCMNT_TMPLT] ([DCMNT_TMPLT_NM], [DCMNT_TMPLT_VERS_NBR])
GO
ALTER TABLE [dbo].[DCMNT] CHECK CONSTRAINT [FK__DCMNT__47DBAE45]
GO
ALTER TABLE [dbo].[DCMNT]  WITH CHECK ADD  CONSTRAINT [FK__DCMNT__48CFD27E] FOREIGN KEY([AAH_CNTRCT_ID], [AAH_CNTRCT_EVNT_NM], [AAH_CNTRCT_EVNT_LOG_DT])
REFERENCES [dbo].[AAH_CNTRCT_EVNT_LOG] ([AAH_CNTRCT_ID], [AAH_CNTRCT_EVNT_NM], [AAH_CNTRCT_EVNT_LOG_DT])
GO
ALTER TABLE [dbo].[DCMNT] CHECK CONSTRAINT [FK__DCMNT__48CFD27E]
GO
ALTER TABLE [dbo].[DCMNT_TMPLT]  WITH CHECK ADD  CONSTRAINT [FK__DCMNT_TMP__DCMNT__46E78A0C] FOREIGN KEY([DCMNT_TMPLT_STAT_NM])
REFERENCES [dbo].[DCMNT_TMPLT_STAT] ([DCMNT_TMPLT_STAT_NM])
GO
ALTER TABLE [dbo].[DCMNT_TMPLT] CHECK CONSTRAINT [FK__DCMNT_TMP__DCMNT__46E78A0C]
GO
ALTER TABLE [dbo].[PICKUP]  WITH CHECK ADD  CONSTRAINT [FK__PICKUP__AAH_CNTR__49C3F6B7] FOREIGN KEY([AAH_CNTRCT_ID])
REFERENCES [dbo].[AAH_CNTRCT] ([AAH_CNTRCT_ID])
GO
ALTER TABLE [dbo].[PICKUP] CHECK CONSTRAINT [FK__PICKUP__AAH_CNTR__49C3F6B7]
GO
ALTER TABLE [dbo].[PICKUP]  WITH CHECK ADD  CONSTRAINT [FK__PICKUP__PICKUP_T__4AB81AF0] FOREIGN KEY([PICKUP_TYPE_NM])
REFERENCES [dbo].[PICKUP_TYPE] ([PICKUP_TYPE_NM])
GO
ALTER TABLE [dbo].[PICKUP] CHECK CONSTRAINT [FK__PICKUP__PICKUP_T__4AB81AF0]
GO
ALTER TABLE [dbo].[SCHED_PICKUP]  WITH CHECK ADD  CONSTRAINT [FK__SCHED_PIC__AAH_C__4CA06362] FOREIGN KEY([AAH_CNTRCT_ID])
REFERENCES [dbo].[AAH_CNTRCT] ([AAH_CNTRCT_ID])
GO
ALTER TABLE [dbo].[SCHED_PICKUP] CHECK CONSTRAINT [FK__SCHED_PIC__AAH_C__4CA06362]
GO
ALTER TABLE [dbo].[SCHED_PICKUP]  WITH CHECK ADD  CONSTRAINT [FK__SCHED_PIC__PICKU__4BAC3F29] FOREIGN KEY([PICKUP_TYPE_NM])
REFERENCES [dbo].[PICKUP_TYPE] ([PICKUP_TYPE_NM])
GO
ALTER TABLE [dbo].[SCHED_PICKUP] CHECK CONSTRAINT [FK__SCHED_PIC__PICKU__4BAC3F29]
GO
