export interface AgreementReport {
    district: string,
    county: string,
    maintenanceOffice: string,
    agreementId: number,
    agreementStatus: string,
    originalContractDate: string,
    lengthOfTimeInProgram: string,
    groupId: number,
    groupName: string,
    segmentId: number,
    segmentStatus: string,
    agreementBeginDate: string,
    agreementEndDate: string,
    signText: string,
    routeName: string,
}