export interface PickupReport {
  id: string,
  lastPickupDate: string,
  nextPickupDate: string,
  renewalDate: string,
  district: string,
  county: string,
  maintenanceOffice: string,
  numberOfMissedPickups: number,
  numberOfPickupsCompleted: number,
  groupId: number,
  groupName: string,
  segmentId: string,
  routeName: string,
  pickupType: string,
  bagQuantityPerGroup: number,
  volumeQuantity: number,
  volunteerCount: number,
  agreementStartDate: string,
  numberOfMiles: number,
}