IF OBJECT_ID('ADDRESS') IS NOT NULL
BEGIN
    DROP TABLE ADDRESS
    PRINT '<<< DROPPED TABLE ADDRESS >>>'
END
;
IF OBJECT_ID('AGREEMENT') IS NOT NULL
BEGIN
    DROP TABLE AGREEMENT
    PRINT '<<< DROPPED TABLE AGREEMENT >>>'
END
;
IF OBJECT_ID('COLUMN_NAME') IS NOT NULL
BEGIN
    DROP TABLE COLUMN_NAME
    PRINT '<<< DROPPED TABLE COLUMN_NAME >>>'
END
;
IF OBJECT_ID('COUNTY') IS NOT NULL
BEGIN
    DROP TABLE COUNTY
    PRINT '<<< DROPPED TABLE COUNTY >>>'
END
;
IF OBJECT_ID('DISTRICT') IS NOT NULL
BEGIN
    DROP TABLE DISTRICT
    PRINT '<<< DROPPED TABLE DISTRICT >>>'
END
;
IF OBJECT_ID('DOCUMENT') IS NOT NULL
BEGIN
    DROP TABLE DOCUMENT
    PRINT '<<< DROPPED TABLE DOCUMENT >>>'
END
;
IF OBJECT_ID('EMAIL') IS NOT NULL
BEGIN
    DROP TABLE EMAIL
    PRINT '<<< DROPPED TABLE EMAIL >>>'
END
;
IF OBJECT_ID('GROUP_SPONSOR') IS NOT NULL
BEGIN
    DROP TABLE GROUP_SPONSOR
    PRINT '<<< DROPPED TABLE GROUP_SPONSOR >>>'
END
;
IF OBJECT_ID('MAINTENANCE_SECTION') IS NOT NULL
BEGIN
    DROP TABLE MAINTENANCE_SECTION
    PRINT '<<< DROPPED TABLE MAINTENANCE_SECTION >>>'
END
;
IF OBJECT_ID('ORGANIZATION') IS NOT NULL
BEGIN
    DROP TABLE ORGANIZATION
    PRINT '<<< DROPPED TABLE ORGANIZATION >>>'
END
;
IF OBJECT_ID('PHONE') IS NOT NULL
BEGIN
    DROP TABLE PHONE
    PRINT '<<< DROPPED TABLE PHONE >>>'
END
;
IF OBJECT_ID('PICKUP') IS NOT NULL
BEGIN
    DROP TABLE PICKUP
    PRINT '<<< DROPPED TABLE PICKUP >>>'
END
;
IF OBJECT_ID('PICKUP_SCHEDULE') IS NOT NULL
BEGIN
    DROP TABLE PICKUP_SCHEDULE
    PRINT '<<< DROPPED TABLE PICKUP_SCHEDULE >>>'
END
;
IF OBJECT_ID('ROLE') IS NOT NULL
BEGIN
    DROP TABLE ROLE
    PRINT '<<< DROPPED TABLE ROLE >>>'
END
;
IF OBJECT_ID('SEGMENT') IS NOT NULL
BEGIN
    DROP TABLE SEGMENT
    PRINT '<<< DROPPED TABLE SEGMENT >>>'
END
;
IF OBJECT_ID('SIGN') IS NOT NULL
BEGIN
    DROP TABLE SIGN
    PRINT '<<< DROPPED TABLE SIGN >>>'
END
;
IF OBJECT_ID('SIGN_STATUS') IS NOT NULL
BEGIN
    DROP TABLE SIGN_STATUS
    PRINT '<<< DROPPED TABLE SIGN_STATUS >>>'
END
;
IF OBJECT_ID('TABLE_NAME') IS NOT NULL
BEGIN
    DROP TABLE TABLE_NAME
    PRINT '<<< DROPPED TABLE TABLE_NAME >>>'
END
;
IF OBJECT_ID('TRANSACTION_LOG') IS NOT NULL
BEGIN
    DROP TABLE TRANSACTION_LOG
    PRINT '<<< DROPPED TABLE TRANSACTION_LOG >>>'
END
;
IF OBJECT_ID('TXDOT') IS NOT NULL
BEGIN
    DROP TABLE TXDOT
    PRINT '<<< DROPPED TABLE TXDOT >>>'
END
;
IF OBJECT_ID('USER_PERSON') IS NOT NULL
BEGIN
    DROP TABLE USER_PERSON
    PRINT '<<< DROPPED TABLE USER_PERSON >>>'
END
;
IF OBJECT_ID('VALUE') IS NOT NULL
BEGIN
    DROP TABLE VALUE
    PRINT '<<< DROPPED TABLE VALUE >>>'
END
;
IF OBJECT_ID('VALUE_RELATIONSHIP') IS NOT NULL
BEGIN
    DROP TABLE VALUE_RELATIONSHIP
    PRINT '<<< DROPPED TABLE VALUE_RELATIONSHIP >>>'
END
;