EXECUTE sp_EXECUTESQL N'
IF NOT EXISTS(SELECT C.NAME AS COLUMN_NAME
FROM SYS.COLUMNS C
    JOIN SYS.TYPES T
    ON C.USER_TYPE_ID=T.USER_TYPE_ID
WHERE C.OBJECT_ID=OBJECT_ID(''DISTRICT'') AND C.NAME = ''NUMBER'')
    BEGIN
    ALTER TABLE DISTRICT ADD NUMBER INT NULL DEFAULT(1);
    END';

EXECUTE sp_EXECUTESQL N'
IF NOT EXISTS(SELECT C.NAME AS COLUMN_NAME
FROM SYS.COLUMNS C
    JOIN SYS.TYPES T
    ON C.USER_TYPE_ID=T.USER_TYPE_ID
WHERE C.OBJECT_ID=OBJECT_ID(''MAINTENANCE_SECTION'') AND C.NAME = ''DISTRICT_NUMBER'')
    BEGIN
    ALTER TABLE MAINTENANCE_SECTION ADD DISTRICT_NUMBER INT NULL DEFAULT(1);
    END';

-- ADD DISTRICT NUMBERS FROM GIS, AND NAMES WHILE WE ARE AT IT SHOULD ALSO MATCH
EXECUTE sp_EXECUTESQL N'
UPDATE d
SET [NUMBER] = g.[DIST_NBR], [NAME] = g.[DIST_NM]
FROM
    [DISTRICT] d
    INNER JOIN [gis].[AAH_GIS_DISTRICTS] g ON d.[CODE] = g.[DIST_ABRVN];';

EXECUTE sp_EXECUTESQL N'
UPDATE ms
SET [DISTRICT_NUMBER] = d.[NUMBER]
FROM
    [MAINTENANCE_SECTION] ms
    INNER JOIN [DISTRICT] d ON d.[DISTRICT_ID] = ms.[DISTRICT_ID];';

-- Now make it not null
EXECUTE sp_EXECUTESQL N'
IF EXISTS(SELECT C.NAME AS COLUMN_NAME,
    TYPE_NAME(C.USER_TYPE_ID) AS DATA_TYPE,
    C.IS_NULLABLE,
    C.MAX_LENGTH,
    C.PRECISION,
    C.SCALE
FROM SYS.COLUMNS C
    JOIN SYS.TYPES T
    ON C.USER_TYPE_ID=T.USER_TYPE_ID
WHERE C.OBJECT_ID=OBJECT_ID(''DISTRICT'') AND C.NAME = ''NUMBER'' AND c.is_nullable = 1)
    BEGIN
	ALTER TABLE
  [DISTRICT]
ALTER COLUMN
  [NUMBER]
    INT NOT NULL
    END
';

EXECUTE sp_EXECUTESQL N'
IF EXISTS(SELECT C.NAME AS COLUMN_NAME,
    TYPE_NAME(C.USER_TYPE_ID) AS DATA_TYPE,
    C.IS_NULLABLE,
    C.MAX_LENGTH,
    C.PRECISION,
    C.SCALE
FROM SYS.COLUMNS C
    JOIN SYS.TYPES T
    ON C.USER_TYPE_ID=T.USER_TYPE_ID
WHERE C.OBJECT_ID=OBJECT_ID(''MAINTENANCE_SECTION'') AND C.NAME = ''DISTRICT_NUMBER'' AND c.is_nullable = 1)
    BEGIN
	ALTER TABLE
  [MAINTENANCE_SECTION]
ALTER COLUMN
  [DISTRICT_NUMBER]
    INT NOT NULL
    END
';
