CREATE OR ALTER PROCEDURE convert_aah_data
AS
BEGIN

	--      execute convert_aah_data

	declare @id					int;
	declare @user_id			int;
	declare @group_id			int;
	declare @organization_id	int;
	declare @district_id		int;
	declare @district_code		char(3);
	declare @district_name		varchar(100);
	declare @maint_id			int;
	declare @maint_name			varchar(100);
	declare @maint_number		int;
	declare @county_code		char(3);
	declare @maint_ml_addr1		varchar(50);
	declare @maint_ml_addr2		varchar(50);
	declare @maint_ml_city		varchar(50);
	declare @maint_ml_state		char(2);
	declare @maint_ml_zip		varchar(10);
	declare @maint_ps_addr1		varchar(50);
	declare @maint_ps_addr2		varchar(50);
	declare @maint_ps_city		varchar(50);
	declare @maint_ps_state		char(2);
	declare @maint_ps_zip		varchar(10);
	declare @maint_home_phone	varchar(10);
	declare @maint_fax_phone	varchar(10);
	declare @maint_create_date	date;
	declare @maint_contact_name	varchar(50);
	declare @maint_email		varchar(50);

	SET IDENTITY_INSERT ORGANIZATION ON;

	INSERT INTO ORGANIZATION
		(ORGANIZATION_ID
		,TYPE)
	SELECT [AAH_GRP_ID]
		, 'Group'
	FROM aah_legacy..AAH_GRP t1
		LEFT JOIN ORGANIZATION t2 on t1.AAH_GRP_ID = t2.ORGANIZATION_ID
	WHERE t2.ORGANIZATION_ID IS NULL;

	SET IDENTITY_INSERT ORGANIZATION OFF;

	SET IDENTITY_INSERT GROUP_SPONSOR ON;

	INSERT INTO [GROUP_SPONSOR]
		([GROUP_ID]
		,[ORGANIZATION_ID]
		,[NAME]
		,[TYPE]
		,[COUNTY_CODE]
		,[ESTIMATED_VOLUNTEER_COUNT]
		,[APPLICATION_SEND_DATE]
		,[INITIAL_CONTACT_DATE]
		,[COMMENT])
	SELECT
		t1.[AAH_GRP_ID]
			, t1.[AAH_GRP_ID]
			, t1.[AAH_GRP_NM]
			, t1.[AAH_GRP_TYPE_NM]
			, t1.[TXDOT_CNTY_NBR]
			, t1.[AAH_GRP_ESTMTD_VOLR_QTY]
			, t1.[AAH_GRP_APPLN_SEND_DT]
			, t1.[AAH_GRP_INIT_CNTCT_DT]
			, t1.[AAH_GRP_CMNT]
	FROM aah_legacy..[AAH_GRP] t1
		LEFT JOIN GROUP_SPONSOR t2 ON t1.AAH_GRP_ID = t2.GROUP_ID
	WHERE t2.GROUP_ID IS NULL;

	SET IDENTITY_INSERT GROUP_SPONSOR OFF;

	SET IDENTITY_INSERT [USER_PERSON] ON;

	INSERT INTO [USER_PERSON]
		([USER_ID]
		,[USERNAME]
		,[PREFIX]
		,[FIRST_NAME]
		,[MIDDLE_NAME]
		,[LAST_NAME]
		,[SUFFIX]
		,[TITLE]
		,[PREFERRED_NAME])
	SELECT [AAH_CNTCT_ID]
	  , SUBSTRING(CNTCT_FRST_NM,1,1) + SUBSTRING(CNTCT_LAST_NM,1,7)
	  , [CNTCT_PRFX_NM]
      , [CNTCT_FRST_NM]
      , [CNTCT_MIDL_NM]
      , [CNTCT_LAST_NM]
      , replace([CNTCT_SFX_NM],'0','')
      , [CNTCT_CRDNTL_NM]
      , [CNTCT_PRFR_NM]
	FROM aah_legacy..aah_cntct t1
		LEFT JOIN USER_PERSON t2 ON t1.AAH_CNTCT_ID = t2.USER_ID
	WHERE t2.USER_ID IS NULL;

	SET IDENTITY_INSERT [USER_PERSON] OFF;

	INSERT INTO ROLE
		(ORGANIZATION_ID, USER_ID, TYPE, START_DATE)
	SELECT AAH_GRP_ID, AAH_CNTCT_ID, 'Volunteer', CREATE_DTTM
	FROM aah_legacy..AAH_GRP_CNTCT t1
		LEFT JOIN ROLE t2 on t1.AAH_GRP_ID = t2.ORGANIZATION_ID AND t1.AAH_CNTCT_ID = t2.USER_ID AND 'Volunteer' = t2.TYPE AND CONVERT(date, t1.CREATE_DTTM, 109) = t2.START_DATE
	WHERE t2.ROLE_ID IS NULL;

	DECLARE district_cursor CURSOR FOR 
	SELECT DISTINCT
		(DIST_ABRVN_NM)
	FROM aah_legacy..MAINT_SECT
	ORDER BY DIST_ABRVN_NM;

	OPEN district_cursor
	FETCH NEXT FROM district_cursor INTO @district_code

	WHILE @@FETCH_STATUS = 0  
BEGIN

		IF @district_code = 'ABL'	SET @district_name = 'Abilene'
		IF @district_code = 'AMA'	SET @district_name = 'Amarillo'
		IF @district_code = 'ATL'	SET @district_name = 'Atlanta'
		IF @district_code = 'AUS'	SET @district_name = 'Austin'
		IF @district_code = 'BMT'	SET @district_name = 'Beaumont'
		IF @district_code = 'BWD'	SET @district_name = 'Brownwood'
		IF @district_code = 'BRY'	SET @district_name = 'Bryan'
		IF @district_code = 'CHS'	SET @district_name = 'Childress'
		IF @district_code = 'CRP'	SET @district_name = 'Corpus Christi'
		IF @district_code = 'ELP'	SET @district_name = 'El Paso'
		IF @district_code = 'DAL'	SET @district_name = 'Dallas'
		IF @district_code = 'FTW'	SET @district_name = 'Fort Worth'
		IF @district_code = 'HOU'	SET @district_name = 'Houston'
		IF @district_code = 'LRD'	SET @district_name = 'Laredo'
		IF @district_code = 'LBB'	SET @district_name = 'Lubbock'
		IF @district_code = 'LFK'	SET @district_name = 'Lufkin'
		IF @district_code = 'ODA'	SET @district_name = 'Odessa'
		IF @district_code = 'PAR'	SET @district_name = 'Paris'
		IF @district_code = 'PHR'	SET @district_name = 'Pharr'
		IF @district_code = 'SJT'	SET @district_name = 'San Angelo'
		IF @district_code = 'SAT'	SET @district_name = 'San Antonio'
		IF @district_code = 'TYL'	SET @district_name = 'Tyler'
		IF @district_code = 'WAC'	SET @district_name = 'Waco'
		IF @district_code = 'WFS'	SET @district_name = 'Wichita Falls'
		IF @district_code = 'YKM'	SET @district_name = 'Yoakum'

        IF NOT EXISTS(SELECT * FROM DISTRICT WHERE CODE = @district_code)
        BEGIN
            INSERT INTO ORGANIZATION
                (TYPE)
            VALUES
            ('District');

            SELECT @organization_id = SCOPE_IDENTITY();
            
		    INSERT INTO DISTRICT
			    (ORGANIZATION_ID
			    ,CODE
			    ,NAME)
		    SELECT
			    @organization_id
		    , @district_code
		    , @district_name
		    WHERE NOT EXISTS (SELECT *
		    FROM DISTRICT t1
		    WHERE t1.CODE = @district_code);
        END

		fetch next from district_cursor into @district_code

	END
	CLOSE district_cursor
	DEALLOCATE district_cursor

	DECLARE maintenance_cursor CURSOR FOR 
	SELECT [MAINT_SECT_NM]
			, [MAINT_SECT_NBR]
			, [DIST_ABRVN_NM]
			, format(TXDOT_CNTY_NBR,'000')
		  , TRIM(UPPER([MAINT_SECT_ML_ADDR1]))
		  , TRIM(UPPER([MAINT_SECT_ML_ADDR2]))
		  , TRIM(UPPER([MAINT_SECT_ML_CITY_NM]))
		  , TRIM(UPPER([MAINT_SECT_ML_STATE_ABRVN_NM]))
		  , TRIM(UPPER([MAINT_SECT_ML_ZIPCD]))
		  , TRIM(UPPER([MAINT_SECT_PHYS_ADDR1]))
		  , TRIM(UPPER([MAINT_SECT_PHYS_ADDR2]))
		  , TRIM(UPPER([MAINT_SECT_PHYS_CITY_NM]))
		  , 'TX'
		  , [MAINT_SECT_PHYS_ZIPCD]
		  , [MAINT_SECT_HOME_PHN_NBR]
		  , [MAINT_SECT_FAX_PHN_NBR]
		  , [CREATE_DTTM]
		  , [MAINT_SECT_CNTCT_NM]
		  , [MAINT_SECT_CNTCT_EML_ADDR]
	FROM aah_legacy..MAINT_SECT
	ORDER BY DIST_ABRVN_NM, MAINT_SECT_NBR;

	OPEN maintenance_cursor
	FETCH NEXT FROM maintenance_cursor 
	INTO 
		 @maint_name,
		 @maint_number,
		 @district_code,
		 @county_code,
		 @maint_ml_addr1,
		 @maint_ml_addr2,
		 @maint_ml_city,
		 @maint_ml_state,
		 @maint_ml_zip,
		 @maint_ps_addr1,
		 @maint_ps_addr2,
		 @maint_ps_city,
		 @maint_ps_state,
		 @maint_ps_zip,
		 @maint_home_phone,
		 @maint_fax_phone,
		 @maint_create_date,
		 @maint_contact_name,
		 @maint_email;
;

	WHILE @@FETCH_STATUS = 0  
    BEGIN

		    INSERT INTO ORGANIZATION
			    (TYPE)
		    SELECT 'Maintenance Section'
		    WHERE NOT EXISTS (SELECT *
		    FROM ORGANIZATION
		    WHERE TYPE = 'Maintenance Section');

		    SELECT @organization_id = SCOPE_IDENTITY();

		    INSERT INTO MAINTENANCE_SECTION
			    (ORGANIZATION_ID
			    ,NAME
			    ,NUMBER
			    ,DISTRICT_CODE
			    ,COUNTY_CODE)
		    SELECT
			    @organization_id
		    , @maint_name
		    , @maint_number
		    , @district_code
		    , @county_code
		    WHERE NOT EXISTS (SELECT *
		    FROM MAINTENANCE_SECTION t1
		    WHERE t1.NAME = @maint_name);

		    IF COALESCE(@maint_contact_name,'') = ''
                SET @maint_contact_name = 'Coordinator Name Needed';

            SET @user_id = NULL

            SELECT @user_id = USER_ID
		    FROM USER_PERSON
		    WHERE FULL_NAME = @maint_contact_name;

            IF @user_id IS NULL
            BEGIN
                INSERT INTO USER_PERSON
			        (FULL_NAME)
		        SELECT @maint_contact_name
		        WHERE NOT EXISTS(SELECT *
		        FROM USER_PERSON
		        WHERE FULL_NAME = @maint_contact_name);

		        SELECT @user_id = SCOPE_IDENTITY();
            END

		    INSERT INTO ROLE
			    (ORGANIZATION_ID,
			    USER_ID,
			    TYPE,
			    START_DATE)
		    SELECT
			    @organization_id,
			    @user_id,
			    'Maintenance Coordinator',
			    @maint_create_date
		    WHERE NOT EXISTS(SELECT *
		    FROM ROLE t1
		    WHERE t1.ORGANIZATION_ID = @organization_id AND t1.USER_ID = @user_id AND t1.TYPE = 'Maintenance Coordinator' AND t1.START_DATE = CONVERT(date, @maint_create_date, 101));                

		    IF COALESCE(@maint_ml_addr1,'') > ''

		    INSERT INTO ADDRESS
			    (USER_ID,
			    PRIMARY_CONTACT,
			    TYPE,
			    ADDRESS_LINE1,
			    ADDRESS_LINE2,
			    CITY,
			    STATE,
			    POSTAL_CODE)
		    SELECT
			    @user_id,
			    'Yes',
			    'Mailing Address',
			    @maint_ml_addr1,
			    @maint_ml_addr2,
			    @maint_ml_city,
			    @maint_ml_state,
			    @maint_ml_zip
		    WHERE NOT EXISTS (
             SELECT *
		    FROM ADDRESS t1
		    WHERE t1.USER_ID = @user_id AND t1.PRIMARY_CONTACT = 'Yes'
			    AND t1.TYPE = 'Mailing Address' 
                AND t1.ADDRESS_LINE1 = @maint_ml_addr1
			    AND t1.ADDRESS_LINE2 = @maint_ml_addr2
			    AND t1.CITY = @maint_ml_city
			    AND t1.POSTAL_CODE = @maint_ml_zip);

		    IF COALESCE(@maint_ps_addr1,'') > ''
            BEGIN
		        INSERT INTO ADDRESS
			        (USER_ID,
			        PRIMARY_CONTACT,
			        TYPE,
			        ADDRESS_LINE1,
			        ADDRESS_LINE2,
			        CITY,
			        STATE,
			        POSTAL_CODE)
		        SELECT
			        @user_id,
			        'Yes',
			        'Physical Address',
			        @maint_ps_addr1,
			        @maint_ps_addr2,
			        @maint_ps_city,
			        @maint_ps_state,
			        @maint_ps_zip
		        WHERE NOT EXISTS (SELECT *
		        FROM ADDRESS t1
		        WHERE t1.USER_ID = @user_id 
                AND TRIM(t1.PRIMARY_CONTACT) = TRIM('Yes')
                AND TRIM(t1.TYPE) = TRIM('Physical Address') 
                AND TRIM(t1.ADDRESS_LINE1) = TRIM(@maint_ps_addr1) 
                AND TRIM(t1.ADDRESS_LINE2) = TRIM(@maint_ps_addr2) 
                AND TRIM(t1.CITY) = TRIM(@maint_ps_city) 
                AND TRIM(t1.POSTAL_CODE) = TRIM(@maint_ps_zip));
            END

		    IF COALESCE(@maint_email,'') > ''
	        BEGIN
		        INSERT INTO EMAIL
			        (USER_ID, TYPE, VALUE)
		        SELECT @user_id, 'Work', @maint_email
		        WHERE NOT EXISTS (SELECT *
		        FROM EMAIL t1
		        WHERE t1.USER_ID = @user_id AND t1.TYPE = 'Work' AND t1.VALUE = @maint_email);
            END

		    IF COALESCE(@maint_home_phone,'') > ''
		    BEGIN 
                INSERT INTO PHONE
			        (USER_ID, TYPE, VALUE)
		        SELECT @user_id, 'Home Phone', @maint_home_phone
		        WHERE NOT EXISTS (SELECT *
		        FROM PHONE t1
		        WHERE t1.USER_ID = @user_id AND t1.TYPE = 'Home Phone' AND t1.VALUE = @maint_home_phone);
            END
		
		    IF COALESCE(@maint_fax_phone,'') > ''
		    BEGIN
		        INSERT INTO PHONE
			        (USER_ID, TYPE, VALUE)
		        SELECT @user_id, 'Fax', @maint_fax_phone
		        WHERE NOT EXISTS (SELECT *
		        FROM PHONE t1
		        WHERE t1.USER_ID = @user_id AND t1.TYPE = 'Fax' AND t1.VALUE = @maint_fax_phone);
            END

		fetch next from maintenance_cursor 
	into @maint_name,
		 @maint_number,
		 @district_code,
		 @county_code,
		 @maint_ml_addr1,
		 @maint_ml_addr2,
		 @maint_ml_city,
		 @maint_ml_state,
		 @maint_ml_zip,
		 @maint_ps_addr1,
		 @maint_ps_addr2,
		 @maint_ps_city,
		 @maint_ps_state,
		 @maint_ps_zip,
		 @maint_home_phone,
		 @maint_fax_phone,
		 @maint_create_date,
		 @maint_contact_name,
		 @maint_email;
;

	END
	CLOSE maintenance_cursor
	DEALLOCATE maintenance_cursor

	SET IDENTITY_INSERT SEGMENT ON;

	INSERT INTO [SEGMENT]
		([SEGMENT_ID]
		,[MAINTENANCE_SECTION_ID]
		,[STATUS]
		,[STATUS_REASON]
		,[LENGTH]
		,[FROM_TO_DESCRIPTION]
		,[ROUTE_PREFIX]
		,[ROUTE_NUMBER]
		,[SUFFIX_NAME]
		,[ACREAGE_MEASURE]
		,[PICKUP_CYCLE]
		,[BASE_SIGN]
		,[FROM_LATTITUDE]
		,[FROM_LONGITUDE]
		,[TO_LATTITUDE]
		,[TO_LONGITUDE]
		,[COMMENT])
	SELECT
		t1.[AAH_SGMNT_ID]
			, M.[MAINTENANCE_SECTION_ID]
			, t1.[AAH_SGMNT_STAT_NM]
			, t1.[AAH_SGMNT_CNSTR_FLAG]
			, t1.[AAH_SGMNT_LNGTH_MS]
			, t1.[FROM_TO_LMT_DSCR]
			, t1.[RTE_PRFX_CD]
			, t1.[RTE_NBR]
			, t1.[RTE_SFX_NM]
			, t1.[AAH_SGMNT_ACRE_MS]
			, t1.[AAH_SGMNT_PICKUP_CYCL_QTY]
			, t1.[AAH_SGMNT_BASE_SIGN_FLAG]
			, COALESCE(t1.[AAH_SGMNT_FROM_LAT],0)
			, COALESCE(t1.[AAH_SGMNT_FROM_LON],0)
			, COALESCE(t1.[AAH_SGMNT_TO_LAT],0)
			, COALESCE(t1.[AAH_SGMNT_TO_LON],0)
			, t1.[AAH_SGMNT_CMNT]
	FROM aah_legacy..[AAH_SGMNT] t1
		INNER JOIN MAINTENANCE_SECTION M ON t1.MAINT_SECT_NBR = M.NUMBER and M.DISTRICT_CODE = t1.DIST_ABRVN_NM
		LEFT JOIN SEGMENT t2 ON t1.AAH_SGMNT_ID = t2.SEGMENT_ID
	WHERE t2.SEGMENT_ID IS NULL;

	SET IDENTITY_INSERT SEGMENT OFF;

	SET IDENTITY_INSERT AGREEMENT ON;

	INSERT INTO [AGREEMENT]
		([AGREEMENT_ID]
		,[GROUP_ID]
		,[SEGMENT_ID]
		,[STATUS]
		,[BEGIN_DATE]
		,[END_DATE])
	SELECT
		t1.[AAH_CNTRCT_ID]
		, t1.[AAH_GRP_ID]
		, t1.[AAH_SGMNT_ID]
		, t1.[AAH_CNTRCT_STAT_NM]
		, t1.[AAH_CNTRCT_START_DT]
		, t1.[AAH_CNTRCT_EXPIR_DT]
	FROM aah_legacy..[AAH_CNTRCT] t1
		LEFT JOIN AGREEMENT t2 ON t1.AAH_CNTRCT_ID = t2.AGREEMENT_ID AND t1.AAH_GRP_ID = t2.GROUP_ID AND t1.AAH_SGMNT_ID = t2.SEGMENT_ID
	WHERE t2.AGREEMENT_ID IS NULL;

	SET IDENTITY_INSERT AGREEMENT OFF;

	INSERT INTO [PICKUP_SCHEDULE]
		([AGREEMENT_ID]
		,[TYPE]
		,[SCHEDULED_PICKUP_YEAR_MONTH]
		,[SCHEDULED_PICKUP_DATE]
		,[ESTIMATED_BAG_QUANTITY]
		,[ESTIMATED_VEST_QUANTITY])
	SELECT
		t1.[AAH_CNTRCT_ID]
		, t1.[PICKUP_TYPE_NM]
		, t1.[SCHED_PICKUP_ESTMTD_MTH_YR_DT]
		, t1.[SCHED_PICKUP_ACTL_SCHED_DT]
		, t1.[SCHED_PICKUP_ESTMTD_BAG_QTY]
		, t1.[SCHED_PICKUP_ESTMTD_VEST_QTY]
	FROM aah_legacy..[SCHED_PICKUP] t1
		LEFT JOIN [PICKUP_SCHEDULE] t2 on t1.AAH_CNTRCT_ID = t2.AGREEMENT_ID AND t1.PICKUP_TYPE_NM = t2.TYPE AND t1.SCHED_PICKUP_ESTMTD_MTH_YR_DT = t2.SCHEDULED_PICKUP_YEAR_MONTH
	WHERE t2.AGREEMENT_ID IS NULL;


	INSERT INTO [PICKUP]
		([AGREEMENT_ID]
		,[TYPE]
		,[ACTUAL_PICKUP_DATE]
		,[BAG_FILL_QUANTITY]
		,[VOLUME_QUANTITY]
		,[UNUSUAL_ITEM_DESCRIPTION]
		,[EXTRA_CLEANUP]
		,[COMMENT])
	SELECT
		[AAH_CNTRCT_ID]
		, [PICKUP_TYPE_NM]
		, [AAH_PICKUP_DT]
		, [PICKUP_BAG_FILL_QTY]
		, [PICKUP_VOLR_QTY]
		, [PICKUP_UNUSL_ITEM_DSCR]
		, [PICKUP_EXTRA_CLEANUP_FLAG]
		, [PICKUP_CMNT]
	FROM aah_legacy..[PICKUP] t1
		LEFT JOIN PICKUP t2 ON  t1.[AAH_CNTRCT_ID] = t2.[AGREEMENT_ID] AND [PICKUP_TYPE_NM] = t2.[TYPE]
			AND [AAH_PICKUP_DT] = t2.[ACTUAL_PICKUP_DATE]
			AND [PICKUP_BAG_FILL_QTY] = t2.[BAG_FILL_QUANTITY]
			AND [PICKUP_VOLR_QTY] = t2.[VOLUME_QUANTITY]
			AND [PICKUP_UNUSL_ITEM_DSCR] = t2.[UNUSUAL_ITEM_DESCRIPTION]
			AND [PICKUP_EXTRA_CLEANUP_FLAG] = t2.EXTRA_CLEANUP
			AND [PICKUP_CMNT] = t2.COMMENT
	WHERE t2.AGREEMENT_ID IS NULL;

	INSERT INTO [DOCUMENT]
		([AGREEMENT_ID]
		,[TEMPLATE_NAME]
		,[SENT_DATE])
	SELECT
		t1.[AAH_CNTRCT_ID]
		, t1.[DCMNT_TMPLT_NM]
		, t1.[AAH_CNTRCT_EVNT_LOG_DT]
	FROM aah_legacy..DCMNT t1
		LEFT JOIN DOCUMENT t2 ON t1.AAH_CNTRCT_ID = t2.AGREEMENT_ID AND t1.DCMNT_TMPLT_NM = t2.TEMPLATE_NAME AND t1.AAH_CNTRCT_EVNT_LOG_DT = t2.SENT_DATE
	WHERE t2.AGREEMENT_ID IS NULL;

	SET IDENTITY_INSERT COUNTY ON;

	INSERT INTO COUNTY
		(COUNTY_ID,
		CODE,
		NAME)
																																																																																																																																																																																																																																																															SELECT 1, '001', 'ANDERSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 1)
	UNION
		SELECT 2, '002', 'ANDREWS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 2)
	UNION
		SELECT 3, '003', 'ANGELINA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 3)
	UNION
		SELECT 4, '004', 'ARANSAS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 4)
	UNION
		SELECT 5, '005', 'ARCHER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 5)
	UNION
		SELECT 6, '006', 'ARMSTRONG'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 6)
	UNION
		SELECT 7, '007', 'ATASCOSA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 7)
	UNION
		SELECT 8, '008', 'AUSTIN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 8)
	UNION
		SELECT 9, '009', 'BAILEY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 9)
	UNION
		SELECT 10, '010', 'BANDERA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 10)
	UNION
		SELECT 11, '011', 'BASTROP'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 11)
	UNION
		SELECT 12, '012', 'BAYLOR'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 12)
	UNION
		SELECT 13, '013', 'BEE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 13)
	UNION
		SELECT 14, '014', 'BELL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 14)
	UNION
		SELECT 15, '015', 'BEXAR'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 15)
	UNION
		SELECT 16, '016', 'BLANCO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 16)
	UNION
		SELECT 17, '017', 'BORDEN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 17)
	UNION
		SELECT 18, '018', 'BOSQUE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 18)
	UNION
		SELECT 19, '019', 'BOWIE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 19)
	UNION
		SELECT 20, '020', 'BRAZORIA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 20)
	UNION
		SELECT 21, '021', 'BRAZOS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 21)
	UNION
		SELECT 22, '022', 'BREWSTER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 22)
	UNION
		SELECT 23, '023', 'BRISCOE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 23)
	UNION
		SELECT 24, '024', 'BROOKS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 24)
	UNION
		SELECT 25, '025', 'BROWN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 25)
	UNION
		SELECT 26, '026', 'BURLESON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 26)
	UNION
		SELECT 27, '027', 'BURNET'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 27)
	UNION
		SELECT 28, '028', 'CALDWELL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 28)
	UNION
		SELECT 29, '029', 'CALHOUN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 29)
	UNION
		SELECT 30, '030', 'CALLAHAN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 30)
	UNION
		SELECT 31, '031', 'CAMERON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 31)
	UNION
		SELECT 32, '032', 'CAMP'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 32)
	UNION
		SELECT 33, '033', 'CARSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 33)
	UNION
		SELECT 34, '034', 'CASS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 34)
	UNION
		SELECT 35, '035', 'CASTRO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 35)
	UNION
		SELECT 36, '036', 'CHAMBERS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 36)
	UNION
		SELECT 37, '037', 'CHEROKEE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 37)
	UNION
		SELECT 38, '038', 'CHILDRESS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 38)
	UNION
		SELECT 39, '039', 'CLAY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 39)
	UNION
		SELECT 40, '040', 'COCHRAN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 40)
	UNION
		SELECT 41, '041', 'COKE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 41)
	UNION
		SELECT 42, '042', 'COLEMAN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 42)
	UNION
		SELECT 43, '043', 'COLLIN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 43)
	UNION
		SELECT 44, '044', 'COLLINGSWORTH'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 44)
	UNION
		SELECT 45, '045', 'COLORADO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 45)
	UNION
		SELECT 46, '046', 'COMAL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 46)
	UNION
		SELECT 47, '047', 'COMANCHE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 47)
	UNION
		SELECT 48, '048', 'CONCHO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 48)
	UNION
		SELECT 49, '049', 'COOKE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 49)
	UNION
		SELECT 50, '050', 'CORYELL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 50)
	UNION
		SELECT 51, '051', 'COTTLE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 51)
	UNION
		SELECT 52, '052', 'CRANE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 52)
	UNION
		SELECT 53, '053', 'CROCKETT'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 53)
	UNION
		SELECT 54, '054', 'CROSBY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 54)
	UNION
		SELECT 55, '055', 'CULBERSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 55)
	UNION
		SELECT 56, '056', 'DALLAM'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 56)
	UNION
		SELECT 57, '057', 'DALLAS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 57)
	UNION
		SELECT 58, '058', 'DAWSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 58)
	UNION
		SELECT 59, '059', 'DEAF SMITH'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 59)
	UNION
		SELECT 60, '060', 'DELTA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 60)
	UNION
		SELECT 61, '061', 'DENTON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 61)
	UNION
		SELECT 62, '062', 'DEWITT'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 62)
	UNION
		SELECT 63, '063', 'DICKENS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 63)
	UNION
		SELECT 64, '064', 'DIMMIT'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 64)
	UNION
		SELECT 65, '065', 'DONLEY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 65)
	UNION
		SELECT 66, '066', 'DUVAL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 66)
	UNION
		SELECT 67, '067', 'EASTLAND'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 67)
	UNION
		SELECT 68, '068', 'ECTOR'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 68)
	UNION
		SELECT 69, '069', 'EDWARDS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 69)
	UNION
		SELECT 70, '070', 'ELLIS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 70)
	UNION
		SELECT 71, '071', 'EL PASO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 71)
	UNION
		SELECT 72, '072', 'ERATH'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 72)
	UNION
		SELECT 73, '073', 'FALLS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 73)
	UNION
		SELECT 74, '074', 'FANNIN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 74)
	UNION
		SELECT 75, '075', 'FAYETTE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 75)
	UNION
		SELECT 76, '076', 'FISHER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 76)
	UNION
		SELECT 77, '077', 'FLOYD'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 77)
	UNION
		SELECT 78, '078', 'FOARD'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 78)
	UNION
		SELECT 79, '079', 'FORT BEND'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 79)
	UNION
		SELECT 80, '080', 'FRANKLIN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 80)
	UNION
		SELECT 81, '081', 'FREESTONE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 81)
	UNION
		SELECT 82, '082', 'FRIO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 82)
	UNION
		SELECT 83, '083', 'GAINES'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 83)
	UNION
		SELECT 84, '084', 'GALVESTON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 84)
	UNION
		SELECT 85, '085', 'GARZA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 85)
	UNION
		SELECT 86, '086', 'GILLESPIE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 86)
	UNION
		SELECT 87, '087', 'GLASSCOCK'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 87)
	UNION
		SELECT 88, '088', 'GOLIAD'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 88)
	UNION
		SELECT 89, '089', 'GONZALES'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 89)
	UNION
		SELECT 90, '090', 'GRAY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 90)
	UNION
		SELECT 91, '091', 'GRAYSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 91)
	UNION
		SELECT 92, '092', 'GREGG'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 92)
	UNION
		SELECT 93, '093', 'GRIMES'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 93)
	UNION
		SELECT 94, '094', 'GUADALUPE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 94)
	UNION
		SELECT 95, '095', 'HALE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 95)
	UNION
		SELECT 96, '096', 'HALL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 96)
	UNION
		SELECT 97, '097', 'HAMILTON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 97)
	UNION
		SELECT 98, '098', 'HANSFORD'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 98)
	UNION
		SELECT 99, '099', 'HARDEMAN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 99)
	UNION
		SELECT 100, '100', 'HARDIN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 100)
	UNION
		SELECT 101, '101', 'HARRIS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 101)
	UNION
		SELECT 102, '102', 'HARRISON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 102)
	UNION
		SELECT 103, '103', 'HARTLEY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 103)
	UNION
		SELECT 104, '104', 'HASKELL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 104)
	UNION
		SELECT 105, '105', 'HAYS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 105)
	UNION
		SELECT 106, '106', 'HEMPHILL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 106)
	UNION
		SELECT 107, '107', 'HENDERSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 107)
	UNION
		SELECT 108, '108', 'HIDALGO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 108)
	UNION
		SELECT 109, '109', 'HILL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 109)
	UNION
		SELECT 110, '110', 'HOCKLEY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 110)
	UNION
		SELECT 111, '111', 'HOOD'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 111)
	UNION
		SELECT 112, '112', 'HOPKINS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 112)
	UNION
		SELECT 113, '113', 'HOUSTON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 113)
	UNION
		SELECT 114, '114', 'HOWARD'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 114)
	UNION
		SELECT 115, '115', 'HUDSPETH'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 115)
	UNION
		SELECT 116, '116', 'HUNT'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 116)
	UNION
		SELECT 117, '117', 'HUTCHINSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 117)
	UNION
		SELECT 118, '118', 'IRION'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 118)
	UNION
		SELECT 119, '119', 'JACK'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 119)
	UNION
		SELECT 120, '120', 'JACKSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 120)
	UNION
		SELECT 121, '121', 'JASPER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 121)
	UNION
		SELECT 122, '122', 'JEFF DAVIS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 122)
	UNION
		SELECT 123, '123', 'JEFFERSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 123)
	UNION
		SELECT 124, '124', 'JIM HOGG'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 124)
	UNION
		SELECT 125, '125', 'JIM WELLS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 125)
	UNION
		SELECT 126, '126', 'JOHNSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 126)
	UNION
		SELECT 127, '127', 'JONES'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 127)
	UNION
		SELECT 128, '128', 'KARNES'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 128)
	UNION
		SELECT 129, '129', 'KAUFMAN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 129)
	UNION
		SELECT 130, '130', 'KENDALL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 130)
	UNION
		SELECT 131, '131', 'KENEDY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 131)
	UNION
		SELECT 132, '132', 'KENT'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 132)
	UNION
		SELECT 133, '133', 'KERR'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 133)
	UNION
		SELECT 134, '134', 'KIMBLE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 134)
	UNION
		SELECT 135, '135', 'KING'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 135)
	UNION
		SELECT 136, '136', 'KINNEY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 136)
	UNION
		SELECT 137, '137', 'KLEBERG'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 137)
	UNION
		SELECT 138, '138', 'KNOX'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 138)
	UNION
		SELECT 139, '139', 'LAMAR'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 139)
	UNION
		SELECT 140, '140', 'LAMB'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 140)
	UNION
		SELECT 141, '141', 'LAMPASAS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 141)
	UNION
		SELECT 142, '142', 'LA SALLE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 142)
	UNION
		SELECT 143, '143', 'LAVACA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 143)
	UNION
		SELECT 144, '144', 'LEE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 144)
	UNION
		SELECT 145, '145', 'LEON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 145)
	UNION
		SELECT 146, '146', 'LIBERTY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 146)
	UNION
		SELECT 147, '147', 'LIMESTONE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 147)
	UNION
		SELECT 148, '148', 'LIPSCOMB'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 148)
	UNION
		SELECT 149, '149', 'LIVE OAK'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 149)
	UNION
		SELECT 150, '150', 'LLANO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 150)
	UNION
		SELECT 151, '151', 'LOVING'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 151)
	UNION
		SELECT 152, '152', 'LUBBOCK'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 152)
	UNION
		SELECT 153, '153', 'LYNN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 153)
	UNION
		SELECT 154, '154', 'MCCULLOCH'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 154)
	UNION
		SELECT 155, '155', 'MCLENNAN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 155)
	UNION
		SELECT 156, '156', 'MCMULLEN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 156)
	UNION
		SELECT 157, '157', 'MADISON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 157)
	UNION
		SELECT 158, '158', 'MARION'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 158)
	UNION
		SELECT 159, '159', 'MARTIN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 159)
	UNION
		SELECT 160, '160', 'MASON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 160)
	UNION
		SELECT 161, '161', 'MATAGORDA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 161)
	UNION
		SELECT 162, '162', 'MAVERICK'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 162)
	UNION
		SELECT 163, '163', 'MEDINA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 163)
	UNION
		SELECT 164, '164', 'MENARD'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 164)
	UNION
		SELECT 165, '165', 'MIDLAND'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 165)
	UNION
		SELECT 166, '166', 'MILAM'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 166)
	UNION
		SELECT 167, '167', 'MILLS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 167)
	UNION
		SELECT 168, '168', 'MITCHELL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 168)
	UNION
		SELECT 169, '169', 'MONTAGUE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 169)
	UNION
		SELECT 170, '170', 'MONTGOMERY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 170)
	UNION
		SELECT 171, '171', 'MOORE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 171)
	UNION
		SELECT 172, '172', 'MORRIS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 172)
	UNION
		SELECT 173, '173', 'MOTLEY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 173)
	UNION
		SELECT 174, '174', 'NACOGDOCHES'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 174)
	UNION
		SELECT 175, '175', 'NAVARRO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 175)
	UNION
		SELECT 176, '176', 'NEWTON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 176)
	UNION
		SELECT 177, '177', 'NOLAN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 177)
	UNION
		SELECT 178, '178', 'NUECES'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 178)
	UNION
		SELECT 179, '179', 'OCHILTREE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 179)
	UNION
		SELECT 180, '180', 'OLDHAM'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 180)
	UNION
		SELECT 181, '181', 'ORANGE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 181)
	UNION
		SELECT 182, '182', 'PALO PINTO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 182)
	UNION
		SELECT 183, '183', 'PANOLA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 183)
	UNION
		SELECT 184, '184', 'PARKER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 184)
	UNION
		SELECT 185, '185', 'PARMER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 185)
	UNION
		SELECT 186, '186', 'PECOS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 186)
	UNION
		SELECT 187, '187', 'POLK'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 187)
	UNION
		SELECT 188, '188', 'POTTER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 188)
	UNION
		SELECT 189, '189', 'PRESIDIO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 189)
	UNION
		SELECT 190, '190', 'RAINS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 190)
	UNION
		SELECT 191, '191', 'RANDALL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 191)
	UNION
		SELECT 192, '192', 'REAGAN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 192)
	UNION
		SELECT 193, '193', 'REAL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 193)
	UNION
		SELECT 194, '194', 'RED RIVER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 194)
	UNION
		SELECT 195, '195', 'REEVES'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 195)
	UNION
		SELECT 196, '196', 'REFUGIO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 196)
	UNION
		SELECT 197, '197', 'ROBERTS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 197)
	UNION
		SELECT 198, '198', 'ROBERTSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 198)
	UNION
		SELECT 199, '199', 'ROCKWALL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 199)
	UNION
		SELECT 200, '200', 'RUNNELS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 200)
	UNION
		SELECT 201, '201', 'RUSK'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 201)
	UNION
		SELECT 202, '202', 'SABINE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 202)
	UNION
		SELECT 203, '203', 'SAN AUGUSTINE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 203)
	UNION
		SELECT 204, '204', 'SAN JACINTO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 204)
	UNION
		SELECT 205, '205', 'SAN PATRICIO'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 205)
	UNION
		SELECT 206, '206', 'SAN SABA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 206)
	UNION
		SELECT 207, '207', 'SCHLEICHER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 207)
	UNION
		SELECT 208, '208', 'SCURRY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 208)
	UNION
		SELECT 209, '209', 'SHACKELFORD'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 209)
	UNION
		SELECT 210, '210', 'SHELBY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 210)
	UNION
		SELECT 211, '211', 'SHERMAN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 211)
	UNION
		SELECT 212, '212', 'SMITH'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 212)
	UNION
		SELECT 213, '213', 'SOMERVELL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 213)
	UNION
		SELECT 214, '214', 'STARR'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 214)
	UNION
		SELECT 215, '215', 'STEPHENS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 215)
	UNION
		SELECT 216, '216', 'STERLING'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 216)
	UNION
		SELECT 217, '217', 'STONEWALL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 217)
	UNION
		SELECT 218, '218', 'SUTTON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 218)
	UNION
		SELECT 219, '219', 'SWISHER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 219)
	UNION
		SELECT 220, '220', 'TARRANT'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 220)
	UNION
		SELECT 221, '221', 'TAYLOR'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 221)
	UNION
		SELECT 222, '222', 'TERRELL'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 222)
	UNION
		SELECT 223, '223', 'TERRY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 223)
	UNION
		SELECT 224, '224', 'THROCKMORTON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 224)
	UNION
		SELECT 225, '225', 'TITUS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 225)
	UNION
		SELECT 226, '226', 'TOM GREEN'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 226)
	UNION
		SELECT 227, '227', 'TRAVIS'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 227)
	UNION
		SELECT 228, '228', 'TRINITY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 228)
	UNION
		SELECT 229, '229', 'TYLER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 229)
	UNION
		SELECT 230, '230', 'UPSHUR'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 230)
	UNION
		SELECT 231, '231', 'UPTON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 231)
	UNION
		SELECT 232, '232', 'UVALDE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 232)
	UNION
		SELECT 233, '233', 'VAL VERDE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 233)
	UNION
		SELECT 234, '234', 'VAN ZANDT'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 234)
	UNION
		SELECT 235, '235', 'VICTORIA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 235)
	UNION
		SELECT 236, '236', 'WALKER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 236)
	UNION
		SELECT 237, '237', 'WALLER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 237)
	UNION
		SELECT 238, '238', 'WARD'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 238)
	UNION
		SELECT 239, '239', 'WASHINGTON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 239)
	UNION
		SELECT 240, '240', 'WEBB'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 240)
	UNION
		SELECT 241, '241', 'WHARTON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 241)
	UNION
		SELECT 242, '242', 'WHEELER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 242)
	UNION
		SELECT 243, '243', 'WICHITA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 243)
	UNION
		SELECT 244, '244', 'WILBARGER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 244)
	UNION
		SELECT 245, '245', 'WILLACY'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 245)
	UNION
		SELECT 246, '246', 'WILLIAMSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 246)
	UNION
		SELECT 247, '247', 'WILSON'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 247)
	UNION
		SELECT 248, '248', 'WINKLER'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 248)
	UNION
		SELECT 249, '249', 'WISE'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 249)
	UNION
		SELECT 250, '250', 'WOOD'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 250)
	UNION
		SELECT 251, '251', 'YOAKUM'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 251)
	UNION
		SELECT 252, '252', 'YOUNG'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 252)
	UNION
		SELECT 253, '253', 'ZAPATA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 253)
	UNION
		SELECT 254, '254', 'ZAVALA'
		WHERE NOT EXISTS (SELECT *
		FROM COUNTY t1
		WHERE t1.COUNTY_ID = 254)

	SET IDENTITY_INSERT COUNTY OFF;

END;