DELETE v
FROM VALUE v 
INNER JOIN COLUMN_NAME c ON v.COLUMN_ID = c.COLUMN_ID
INNER JOIN TABLE_NAME t on c.TABLE_ID = t.TABLE_ID
WHERE 
v.VALID_VALUE LIKE '%REACTIVATE%'
AND t.NAME = 'SEGMENT'
AND c.NAME = 'STATUS';

