IF NOT EXISTS(SELECT * FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID WHERE o.type = 'U' and o.name = 'USER_PERSON' AND c.name = 'CURRENT_HASHED_REFRESH_TOKEN')
BEGIN
    ALTER TABLE USER_PERSON ADD
	CURRENT_HASHED_REFRESH_TOKEN varchar(255) NULL
END