CREATE
    OR ALTER PROCEDURE aah_insert_missing_documents
AS
BEGIN;
    SET NOCOUNT ON;
    INSERT INTO [DOCUMENT]
        (
        [AGREEMENT_ID],
        [TEMPLATE_NAME],
        [SENT_DATE]
        )
    SELECT DISTINCT t1.[AAH_CNTRCT_ID],
        t1.[DCMNT_TMPLT_NM],
        t1.[AAH_CNTRCT_EVNT_LOG_DT]
    FROM aah_legacy..DCMNT t1
        LEFT JOIN DOCUMENT t2 ON t1.AAH_CNTRCT_ID = t2.AGREEMENT_ID
            AND t1.DCMNT_TMPLT_NM = t2.TEMPLATE_NAME
            AND CONVERT(CHAR(22), t1.AAH_CNTRCT_EVNT_LOG_DT, 100) = CONVERT(CHAR(22), t2.SENT_DATE, 100)
    WHERE t2.AGREEMENT_ID IS NULL;
    SET NOCOUNT OFF;
END;
