/**

Adds APPLICATION_TOKEN to the AGREEMENT and DOCUMENT tables

*/

ALTER TABLE DOCUMENT ALTER COLUMN TEMPLATE_NAME VARCHAR(3000);

IF NOT EXISTS(SELECT *
FROM sys.columns c
    INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' AND o.name = 'AGREEMENT' AND c.name = 'APPLICATION_TOKEN')
BEGIN
    ALTER TABLE AGREEMENT ADD
	APPLICATION_TOKEN UNIQUEIDENTIFIER NULL
END;

IF NOT EXISTS(SELECT *
FROM sys.columns c
    INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' AND o.name = 'DOCUMENT' AND c.name = 'APPLICATION_TOKEN')
BEGIN
    ALTER TABLE DOCUMENT ADD
	APPLICATION_TOKEN UNIQUEIDENTIFIER NULL
END;

IF NOT EXISTS(SELECT *
FROM sys.columns c
    INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' AND o.name = 'DOCUMENT' AND c.name = 'STATUS')
BEGIN
    ALTER TABLE DOCUMENT ADD
	STATUS VARCHAR(50) NULL
END;


IF NOT EXISTS(SELECT *
FROM sys.columns c
    INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' AND o.name = 'DOCUMENT' AND c.name = 'AGREEMENT_ID')
BEGIN
    ALTER TABLE DOCUMENT ADD
	AGREEMENT_ID INT NOT NULL
END;

-- add foreign key to AGREEMENT
IF OBJECT_ID('[FK_DOCUMENT_AGREEMENT]') IS NULL 
BEGIN;
    ALTER TABLE [DOCUMENT]  WITH CHECK ADD  CONSTRAINT [FK_DOCUMENT_AGREEMENT] FOREIGN KEY([AGREEMENT_ID])
    REFERENCES [AGREEMENT] ([AGREEMENT_ID]);
END;
