-- add foreign key to email
IF OBJECT_ID('[FK_EMAIL_USER_PERSON]') IS NULL 
BEGIN;
    ALTER TABLE [EMAIL]  WITH CHECK ADD  CONSTRAINT [FK_EMAIL_USER_PERSON] FOREIGN KEY([USER_ID])
    REFERENCES [USER_PERSON] ([USER_ID])
    ON UPDATE CASCADE
    ON DELETE CASCADE;
END;

-- can run multiple times
ALTER TABLE [EMAIL] CHECK CONSTRAINT [FK_EMAIL_USER_PERSON];

-- add foreign key to phone
IF OBJECT_ID('[FK_PHONE_USER_PERSON]') IS NULL 
BEGIN;
    ALTER TABLE [PHONE]  WITH CHECK ADD  CONSTRAINT [FK_PHONE_USER_PERSON] FOREIGN KEY([USER_ID])
    REFERENCES [USER_PERSON] ([USER_ID])
    ON UPDATE CASCADE
    ON DELETE CASCADE;
END;

-- can run multiple times
ALTER TABLE [PHONE] CHECK CONSTRAINT [FK_PHONE_USER_PERSON];

-- add foreign key to address
IF OBJECT_ID('[FK_ADDRESS_USER_PERSON]') IS NULL 
BEGIN;
    ALTER TABLE [ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_ADDRESS_USER_PERSON] FOREIGN KEY([USER_ID])
    REFERENCES [USER_PERSON] ([USER_ID])
    ON UPDATE CASCADE
    ON DELETE CASCADE;

    -- can run multiple times
    ALTER TABLE [ADDRESS] CHECK CONSTRAINT [FK_ADDRESS_USER_PERSON];
END;

-- add foreign key to role
IF OBJECT_ID('[FK_ROLE_USER_PERSON]') IS NULL 
BEGIN;
    ALTER TABLE [ROLE]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_USER_PERSON] FOREIGN KEY([USER_ID])
    REFERENCES [USER_PERSON] ([USER_ID]);
END;

-- add foreign key to role
IF OBJECT_ID('[FK_ROLE_USER_PERSON]') IS NOT NULL 
BEGIN;
    -- can run multiple times
    ALTER TABLE [ROLE] CHECK CONSTRAINT [FK_ROLE_USER_PERSON];
END;

-- add foreign key to role
IF OBJECT_ID('[FK_ROLE_ORGANIZATION]') IS NULL 
BEGIN;
    ALTER TABLE [ROLE]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_ORGANIZATION] FOREIGN KEY([ORGANIZATION_ID])
    REFERENCES [ORGANIZATION] ([ORGANIZATION_ID]);
END;

IF OBJECT_ID('[FK_ROLE_ORGANIZATION]') IS NOT NULL 
BEGIN;
	-- can run multiple times
	ALTER TABLE [ROLE] CHECK CONSTRAINT [FK_ROLE_ORGANIZATION];
END;

IF OBJECT_ID('[DF_ROLE_START_DATE]') IS NULL 
BEGIN;
    -- add a default for start date
    ALTER TABLE [ROLE] 
    ADD CONSTRAINT DF_ROLE_START_DATE
    DEFAULT GETDATE() FOR [START_DATE];
END;
