IF OBJECT_ID('AUDIT_LOG') IS NULL AND OBJECT_ID('TRANSACTION_LOG') IS NOT NULL
BEGIN
    exec sp_rename 'TRANSACTION_LOG', 'AUDIT_LOG';
END

IF OBJECT_ID('AUDIT_LOG') IS NOT NULL
BEGIN
    ALTER TABLE AUDIT_LOG ALTER COLUMN ACTION VARCHAR(10);
END