/**
Adds email and county fields for applications to match PDF application form
*/

IF (OBJECT_ID('APPLICATIONS') IS NULL)
BEGIN;
    THROW 51000, 'APPLICATIONS table does not exist', 1;
END;

ALTER TABLE [APPLICATIONS] DROP COLUMN [COUNTY];   
ALTER TABLE [APPLICATIONS] DROP COLUMN [REQUESTED_HIGHWAY_COUNTY];      
ALTER TABLE [APPLICATIONS] ADD GROUP_COUNTY_NUMBER SMALLINT NULL;
ALTER TABLE [APPLICATIONS] ADD REQUESTED_HIGHWAY_COUNTY_NUMBER SMALLINT NULL;
ALTER TABLE [APPLICATIONS] ADD PRIMARY_CONTACT_EMAIL VARCHAR(255) NULL;
ALTER TABLE [APPLICATIONS] ADD PRIMARY_CONTACT_COUNTY_NUMBER SMALLINT NULL;
ALTER TABLE [APPLICATIONS] ADD SECONDARY_CONTACT_EMAIL VARCHAR(255) NULL;
ALTER TABLE [APPLICATIONS] ADD SECONDARY_CONTACT_COUNTY_NUMBER SMALLINT NULL;