/**
Removes APPLICATION_TOKEN column from the AGREEMENT table
Removes AGREEMENT_ID, STATUS, and APPLICATION_TOKEN columns and FK from the DOCUMENT tables

*/

IF EXISTS(SELECT * FROM sys.columns c 
INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID 
WHERE o.type = 'U' AND o.name = 'AGREEMENT' AND c.name = 'APPLICATION_TOKEN')
BEGIN
    ALTER TABLE AGREEMENT DROP COLUMN APPLICATION_TOKEN;
END;

IF EXISTS(SELECT * FROM sys.columns c 
INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID 
WHERE o.type = 'U' AND o.name = 'DOCUMENT' AND c.name = 'APPLICATION_TOKEN')
BEGIN
    ALTER TABLE DOCUMENT DROP COLUMN APPLICATION_TOKEN;
END;

IF EXISTS(SELECT * FROM sys.columns c 
INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID 
WHERE o.type = 'U' AND o.name = 'DOCUMENT' AND c.name = 'STATUS')
BEGIN
    ALTER TABLE DOCUMENT DROP COLUMN STATUS;
END;

IF OBJECT_ID('[FK_DOCUMENT_AGREEMENT]') IS NOT NULL 
BEGIN
    ALTER TABLE DOCUMENT DROP CONSTRAINT FK_DOCUMENT_AGREEMENT;
END