-- AGREEMENT_START_DATE AS DATETIME2

--
-- Add a new agreement start date column
--
IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'AGREEMENT_START_DATE')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN AGREEMENT_START_DATE;
END

-- AGREEMENT_END_DATE AS DATETIME2

--
-- Add a new agreement end date column
--
IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'AGREEMENT_END_DATE')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN AGREEMENT_END_DATE;
END

-- LENGTH_OF_ADOPTED_SECTION AS DECIMAL

IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'LENGTH_OF_ADOPTED_SECTION')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN LENGTH_OF_ADOPTED_SECTION;
END

-- CLEANING_CYCLE_OF_ADOPTED_SECTION AS INT

IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'CLEANING_CYCLE_OF_ADOPTED_SECTION')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN CLEANING_CYCLE_OF_ADOPTED_SECTION;
END

-- TXDOT_CONTACT_FULL_NAME AS NVARCHAR(255)
IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'TXDOT_CONTACT_FULL_NAME')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN TXDOT_CONTACT_FULL_NAME;
END

-- TXDOT_CONTACT_PHONE_NUMBER AS NVARCHAR(20)

IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'TXDOT_CONTACT_PHONE_NUMBER')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN TXDOT_CONTACT_PHONE_NUMBER;
END


-- REQUIRED_PICKUPS_PER_YEAR AS INT

IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'REQUIRED_PICKUPS_PER_YEAR')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN REQUIRED_PICKUPS_PER_YEAR;
END

--
-- Add a new pickups per year column
--
IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'REQUIRED_PICKUPS_PER_YEAR')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN REQUIRED_PICKUPS_PER_YEAR;
END

-- PICKUPS_START_DATE AS DATETIME2

--
-- Add a new pickups start date column
--
IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'PICKUPS_START_DATE')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN PICKUPS_START_DATE;
END


-- PICKUPS_END_DATE AS DATETIME2

--
-- Add a new pickups end date column
--
IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'PICKUPS_END_DATE')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN PICKUPS_END_DATE;
END

-- FIRST_SCHEDULED_PICKUP AS DATETIME2

--
-- Add a new first schedule pickups date column
--
IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'FIRST_SCHEDULED_PICKUP')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN FIRST_SCHEDULED_PICKUP;
END

