-- TXDOT_CONTACT_EMAIL AS NVARCHAR(255)
IF EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'TXDOT_CONTACT_EMAIL')
BEGIN
    ALTER TABLE [APPLICATIONS] DROP COLUMN TXDOT_CONTACT_EMAIL;
END

