--
-- ADD the AGREEMENT.RENEWAL_NOTICE_SENT
--
IF NOT EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'AGREEMENT' AND c.name = 'RENEWAL_NOTICE_SENT')
BEGIN
    ALTER TABLE [AGREEMENT] ADD [RENEWAL_NOTICE_SENT] BIT DEFAULT(0) NOT NULL
END

--
-- Creates the VIEW_RENEWAL_AGREEMENT for showing renewal agreements filtered and sorted
--
EXEC sp_executeSQL N'CREATE OR ALTER VIEW VIEW_RENEWAL_AGREEMENT
AS
    SELECT
        a.AGREEMENT_ID,
        DATEDIFF(dd, GETDATE(), a.END_DATE) as DATEDIFF,
        a.END_DATE AS AGREEMENT_END_DATE, gs.NAME as GROUP_NAME , d.NAME as DISTRICT_NAME, o.NAME as OFFICE_NAME, c.NAME As COUNTY_NAME, s.AAH_ROUTE_NAME, s.AAH_SEGMENT_ID, s.GlobalID, DATEDIFF(dd, GETDATE(), a.END_DATE) AS RENEWAL_DAYS_REMAINING
, d.NUMBER AS DISTRICT_NUMBER, o.NUMBER as OFFICE_NUMBER, c.NUMBER as COUNTY_NUMBER, a.RENEWAL_NOTICE_SENT
, COUNT(p.PICKUP_ID) AS PICKUP_COUNT
    FROM "aah"."AGREEMENT" "a"
        LEFT JOIN "aah"."GROUP_SPONSOR" "gs" ON "a"."GROUP_ID" = "gs"."GROUP_ID"
        LEFT JOIN "aah"."PICKUP" "p" ON "a"."AGREEMENT_ID" = "p"."AGREEMENT_ID"
        LEFT JOIN "gis"."AAH_GIS_SEGMENTS" "s" ON CAST("a"."AAH_SEGMENT_GLOBAL_ID" as VARCHAR(255)) = CAST(s.GlobalID AS VARCHAR(255))
        LEFT JOIN "aah"."DISTRICT" "d" ON "s"."DIST_NBR" = "d"."NUMBER"
        LEFT JOIN "aah"."COUNTY" "c" ON "s".CNTY_NBR = "c"."NUMBER"
        LEFT JOIN "aah"."MAINTENANCE_SECTION" "o" ON "s"."DIST_NBR" = o.DISTRICT_NUMBER AND "s"."MNT_SEC_NBR" = "o"."NUMBER"
    WHERE  
        a.STATUS = ''Renewal Pending''
    GROUP BY 
a.AGREEMENT_ID, a.END_DATE, gs.NAME, d.NAME, o.NAME, c.NAME, s.AAH_ROUTE_NAME, s.AAH_SEGMENT_ID, s.GlobalID, d.NUMBER, o.NUMBER, c.NUMBER, a.RENEWAL_NOTICE_SENT;
;';


