IF NOT EXISTS(SELECT *
FROM sys.columns c INNER JOIN sys.objects o on o.OBJECT_ID = c.OBJECT_ID
WHERE o.type = 'U' and o.name = 'APPLICATIONS' AND c.name = 'TXDOT_CONTACT_USER_ID')
BEGIN
    ALTER TABLE APPLICATIONS ADD
	TXDOT_CONTACT_USER_ID INT NULL;
END

